local min, floor = math.min, math.floor
local ilLerp = MATH.ilLerp
local function floorRank(l0, l1, l2, l3, l4, l5, l6)
    local l = {
        Floors[l0 - 1].top,
        Floors[l1 - 1].top,
        Floors[l2 - 1].top,
        Floors[l3 - 1].top,
        Floors[l4 - 1].top,
        Floors[l5 - 1].top,
        l6 <= 10 and Floors[l6 - 1].top or l6,
    }
    assert(#l == 7)
    return function(h) return min(6 * ilLerp(l, h), 5.9999) end
end
local function numberRank(...)
    local l = { ... }
    assert(#l == 7)
    return function(s) return min(6 * ilLerp(l, s), 5.9999) end
end
local function numberRankRev(...)
    local l = TABLE.reverse { ... }
    assert(#l == 7)
    return function(s) return min(6 * (1 - ilLerp(l, s)), 5.9999) end
end
local function heightFloor(h)
    for i = 9, 0, -1 do
        if h >= Floors[i].top then
            return "FLOOR " .. (i + 1)
        end
    end
end
local function heightNumber(score)
    return string.format("%.1fm", score)
end

---@class Achievement
---@field title? string
---@field ex? true Extended by Zenith Clicker
---@field id? string
---@field name? string
---@field desc? string
---@field quote? string
---@field credit? string
---@field comp? '<' | '>' | fun(newScore, oldScore):boolean
---@field noScore? number
---@field scoreSimp? fun(score):string
---@field scoreFull? fun(score):string
---@field rank? 'floor' | fun(score):number
---@field type? 'competitive' | 'issued' | 'event'
---@field hide? fun():boolean
---@field notUsed? true

---@type Map<Achievement>
Achievements = {
    { title = "General" },
    {},
    { -- zenith_explorer
        id = 'zenith_explorer',
        name = "Zenith Explorer",
        desc = [[HFD without any mods]],
        quote = [[Uncover the mysteries of the Zenith Tower.]],
    },
    { -- zenith_explorer_plus
        ex = true,
        id = 'zenith_explorer_plus',
        name = "Zenith Explorer+",
        desc = [[HFD]],
        quote = [[Uncover the mysteries of the Zenith Tower.]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 8000),
    },
    { -- clicker_speedrun
        ex = true,
        id = 'clicker_speedrun',
        name = "Clicker Speedrun",
        desc = [[Minimal time on 40 quests without any mods]],
        quote = [[Supercharged Q40%]],
        comp = '<',
        scoreSimp = function(time) return string.format("%.2fs", time) end,
        rank = numberRankRev(94.2, 72, 55, 42, 33, 26, 20),
    },
    { -- typer_speedrun
        ex = true,
        id = 'typer_speedrun',
        name = "Typer Speedrun",
        desc = [[Minimal time on 40 quests]],
        quote = [[Supercharged AnyQ40%]],
        comp = '<',
        scoreSimp = function(time) return string.format("%.2fs", time) end,
        rank = numberRankRev(72, 55, 42, 33, 26, 22, 19),
    },
    { -- supercharged
        id = 'supercharged',
        name = "Supercharged",
        desc = [[Highest Back-to-Back chain reached without any mods]],
        quote = [["With this divine power, we'll be unstoppable!" -Mathis, Core Engineer]],
        scoreSimp = function(b2b) return "B2B x" .. b2b end,
        rank = numberRank(0, 20, 40, 65, 90, 120, 180),
    },
    { -- supercharged_plus
        ex = true,
        id = 'supercharged_plus',
        name = "Supercharged+",
        desc = [[Highest Back-to-Back chain reached]],
        quote = [[Supercharged Any%]],
        scoreSimp = function(b2b) return "B2B x" .. b2b end,
        rank = numberRank(0, 20, 40, 65, 90, 120, 180),
    },
    { -- multitasker
        ex = true,
        id = 'multitasker',
        name = "Multitasker",
        desc = [[Highest altitude*modPoints]],
        quote = [[Master doing everything, then master doing everything.]],
        credit = "@Flowerling",
        rank = numberRank(0, 4200, 6200, 9420, 12600, 16200, 26000),
        scoreSimp = function(mmp) return floor(mmp) .. "m·MP" end,
        hide = TRUE,
    },
    { -- effective
        ex = true,
        id = 'effective',
        name = "Effective",
        desc = [[Highest altitude*ZPmul]],
        quote = [[Master doing everything efficiently.]],
        rank = numberRank(0, 2600, 4200, 6200, 10000, 12600, 16200),
        scoreSimp = function(zp) return floor(zp) .. " ZP" end,
        hide = TRUE,
    },
    { -- zenith_speedrun
        id = 'zenith_speedrun',
        name = "Zenith Speedrun",
        desc = [[Reach F10 as fast as possible while retaining GIGASPEED without any mods]],
        quote = [[F10 Hyper%]],
        comp = '<',
        scoreSimp = function(time) return string.format("%.2fs", time) end,
        rank = numberRankRev(180, 120, 100, 90, 82.6, 76.2, 62.6),
        hide = function() return STAT.totalGiga == 0 end,
    },
    { -- zenith_speedrun_plus
        ex = true,
        id = 'zenith_speedrun_plus',
        name = "Zenith Speedrun+",
        desc = [[Reach F10 as fast as possible while retaining GIGASPEED]],
        quote = [[F10 Any%]],
        comp = '<',
        scoreSimp = function(time) return string.format("%.2fs", time) end,
        rank = numberRankRev(180, 120, 100, 90, 82.6, 76.2, 56.7),
        hide = function() return STAT.totalGiga == 0 end,
    },
    { -- zenith_challenger
        ex = true,
        id = 'zenith_challenger',
        name = "Zenith Challenger",
        desc = [[Total best altitude with 1 mod enabled]],
        quote = [[Challenge the reality of the Zenith Tower.]],
        credit = "@5han",
        rank = numberRank(0, 14000, 26000, 36000, 42000, 46000, 60000),
        scoreSimp = function(h) return string.format("%.0fm", h) end,
        hide = TRUE,
    },
    { -- divine_challenger
        ex = true,
        id = 'divine_challenger',
        name = "Divine Challenger",
        desc = [[Total best altitude with 1 rev mod enabled]],
        quote = [[Expose the darkness of the Zenith Tower.]],
        rank = numberRank(0, 10000, 16000, 20000, 24000, 26000, 30000),
        scoreSimp = function(h) return string.format("%.0fm", h) end,
        hide = TRUE,
    },
    { -- zenith_speedrunner
        ex = true,
        id = 'zenith_speedrunner',
        name = "Zenith Speedrunner",
        desc = [[Sum of best F10 time with GIGASPEED using each mod]],
        quote = [[F10 All%]],
        comp = '<',
        scoreSimp = function(time) return string.format("%.2fs", time) end,
        rank = numberRankRev(2600, 2000, 1500, 1260, 1100, 1000, 900),
        hide = TRUE,
    },
    { -- divine_speedrunner
        ex = true,
        id = 'divine_speedrunner',
        name = "Divine Speedrunner",
        desc = [[Sum of best F10 time with GIGASPEED using each rev mod]],
        quote = [[F10 All+%]],
        comp = '<',
        scoreSimp = function(time) return string.format("%.2fs", time) end,
        rank = numberRankRev(12600, 9420, 8720, 7023, 6200, 3600, 1260),
        hide = TRUE,
    },
    { -- the_spike_of_all_time
        id = 'the_spike_of_all_time',
        name = "The Spike of All Time",
        desc = [[Largest spike sent (excluding Surge)]],
        quote = [[Flashy techniques are a staple amongst the glory-seeking competitors.]],
        rank = numberRank(0, 12, 20, 26, 42, 62, 100),
        scoreSimp = function(spike) return floor(spike) .. " Spike" end,
    },
    { -- vip_list
        id = 'vip_list',
        name = "VIP List",
        desc = [[Master the daily combo with any reversed mod included.]],
        quote = [[Unparalleled luxury for a select few.]],
        rank = numberRank(0, 0, 0, 1, 2, 4, 6),
        scoreSimp = function(day) return day == 1 and "1 Day" or day .. " Days" end,
        hide = TRUE,
    },

    { title = "Mods" },
    {},
    { -- EX
        id = 'EX',
        name = "The Emperor",
        desc = [[HFD with the "Expert Mode" mod]],
        quote = [[A display of power for those willing to bear its burden.]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 4200),
    },
    { -- NH
        id = 'NH',
        name = "Temperance",
        desc = [[HFD with the "No Hold" mod]],
        quote = [[Use each piece as they come and embrace the natural flow of stacking.]],
    },
    { -- MS
        id = 'MS',
        name = "Wheel of Fortune",
        desc = [[HFD with the "Messier Garbage" mod]],
        quote = [[The only constant in life is change.]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 4200),
    },
    { -- GV
        id = 'GV',
        name = "The Tower",
        desc = [[HFD with the "Gravity" mod]],
        quote = [[What will you do when it all comes crumbling down?]],
    },
    { -- VL
        id = 'VL',
        name = "Strength",
        desc = [[HFD with the "Volatile Garbage" mod]],
        quote = [[Match great obstacles with greater determination.]],
    },
    { -- DH
        id = 'DH',
        name = "The Devil",
        desc = [[HFD with the "Double Hole" mod]],
        quote = [[Redifine your limits or succumb to his chains.]],
    },
    { -- IN
        id = 'IN',
        name = "The Hermit",
        desc = [[HFD with the "Invisible" mod]],
        quote = [[When the outside world fails you, trust the voice within to light a path.]],
    },
    { -- AS
        id = 'AS',
        name = "The Magician",
        desc = [[HFD with the "All-Spin" mod]],
        quote = [[Inspiration is nothing short of magic.]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 7200),
    },
    { -- DP
        id = 'DP',
        name = "The Lovers",
        desc = [[HFD with the "Duo" mod]],
        quote = [[Love, and resign yourself to the fate of another.]],
    },
    { -- GVIN
        id = 'GVIN',
        name = "The Grandmaster",
        desc = [[HFD WUT "Gravity" and "Invisible" mods]],
        quote = [[When the world descends into chaos, the grandmaster remains at peace.]],
    },
    { -- ASNH
        id = 'ASNH',
        name = "The Starving Artist",
        desc = [[HFD WUT "No Hold" and "All-Spin" mods]],
        quote = [[Creativity cultivated trough limitation.]],
    },
    { -- DPEX
        id = 'DPEX',
        name = "Trained Professionals",
        desc = [[HFD WUT "Expert Mode" and "Duo" mods]],
        quote = [[Partners in expertise.]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 4200),
    },
    { -- GVNH
        id = 'GVNH',
        name = "A Modern Classic",
        desc = [[HFD WUT "No Hold" and "Gravity" mods]],
        quote = [[Times were different back then...]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 4200),
    },
    { -- DHMSNH
        id = 'DHMSNH',
        name = "Deadlock",
        desc = [[HFD WUT "No Hold", "Messier Garbage" and "Double Hole" mods]],
        quote = [["Escape has become a distant dream, yet still we struggle..."]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 2600),
    },
    { -- DHEXNH
        id = 'DHEXNH',
        name = "Emperor's Decadence",
        desc = [[HFD WUT "Expert Mode", "No Hold" and "Double Hole" mods]],
        quote = [[The Devil's lesson in humility.]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 2600),
    },
    { -- DHEXMSVL
        id = 'DHEXMSVL',
        name = "Divine Mastery",
        desc = [[HFD WUT "Expert Mode", "Messier Garbage", "Volatile Garbage" and "Double Hole" mods]],
        quote = [[The universe is yours.]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 2600),
    },
    { -- ASEXVL
        id = 'ASEXVL',
        name = "The Con Artist",
        desc = [[HFD WUT "Expert Mode", "Volatile Garbage" and "All-Spin" mods]],
        quote = [[Would the perfect lie not be an art worthy of admiration ?]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 2600),
    },
    { -- swamp_water_lite
        id = 'swamp_water_lite',
        name = "Swamp Water Lite",
        desc = [[HFD WUT all 7/8 of the difficulty mods ("Duo" not allowed)]],
        quote = [[Comes in 8 different flavors!]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 2600),
    },
    { -- swamp_water
        id = 'swamp_water',
        name = "Swamp Water",
        desc = [[HFD WUT all mods other than "Duo" at the same time]],
        quote = [[The worst of all worlds.]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 2200),
    },
    { -- swamp_water_pro
        ex = true,
        id = 'swamp_water_pro',
        name = "Swamp Water Pro",
        desc = [[HFD WUT all mods at the same time]],
        quote = [[How did you find someone as insane as you to do it together?]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 2000),
    },

    { title = "Reversed Mods", hide = function() return TABLE.countAll(GAME.completion, 0) == 9 end },
    {},
    { -- rEX
        id = 'rEX',
        name = "The Tyrant",
        desc = [[HFD with the reversed "Expert Mode" mod]],
        quote = [[Fear, oppression, and limitless ambition.]],
        hide = function() return GAME.completion.EX == 0 end,
        rank = floorRank(1, 3, 5, 7, 9, 10, 1800),
    },
    { -- rNH
        id = 'rNH',
        name = "Asceticism",
        desc = [[HFD with the reversed "No Hold" mod]],
        quote = [[A detachment from even that which is moderate.]],
        hide = function() return GAME.completion.NH == 0 end,
        rank = floorRank(1, 3, 5, 7, 9, 10, 2600),
    },
    { -- rMS
        id = 'rMS',
        name = "Loaded Dice",
        desc = [[HFD with the reversed "Messier Garbage" mod]],
        quote = [[In a rigged game, your mind is the only fair advantage.]],
        hide = function() return GAME.completion.MS == 0 end,
        rank = floorRank(1, 3, 5, 7, 9, 10, 2600),
    },
    { -- rGV
        id = 'rGV',
        name = "Freefall",
        desc = [[HFD with the reversed "Gravity" mod]],
        quote = [[In retrospect, the ground you stood on never existed in the first place.]],
        hide = function() return GAME.completion.GV == 0 end,
        rank = floorRank(1, 3, 5, 7, 9, 10, 4200),
    },
    { -- rVL
        id = 'rVL',
        name = "Last Stand",
        desc = [[HFD with the reversed "Volatile Garbage" mod]],
        quote = [[Strength isn't necessary for those with nothing to lose.]],
        hide = function() return GAME.completion.VL == 0 end,
        rank = floorRank(1, 3, 5, 7, 9, 10, 4200),
    },
    { -- rDH
        id = 'rDH',
        name = "Damnation",
        desc = [[HFD with the reversed "Double Hole" mod]],
        quote = [[Neither the freedom of life or peace of death.]],
        hide = function() return GAME.completion.DH == 0 end,
        rank = floorRank(1, 3, 5, 7, 9, 10, 2200),
    },
    { -- rIN
        id = 'rIN',
        name = "The Exile",
        desc = [[HFD with the reversed "Invisible" mod]],
        quote = [[Never underestimate blind faith.]],
        hide = function() return GAME.completion.IN == 0 end,
        rank = floorRank(1, 3, 5, 7, 9, 10, 2600),
    },
    { -- rAS
        id = 'rAS',
        name = "The Warlock",
        desc = [[HFD with the reversed "All-Spin" mod]],
        quote = [[Into realms beyond heaven and earth.]],
        hide = function() return GAME.completion.AS == 0 end,
    },
    { -- rDP
        id = 'rDP',
        name = "Bleeding Hearts",
        desc = [[HFD with the reversed "Duo" mod]],
        quote = [[Even as we bleed, we keep holding on...]],
        hide = function() return GAME.completion.DP == 0 end,
        rank = floorRank(1, 3, 5, 7, 9, 10, 2200),
    },
    { -- DHEXrGV
        ex = true,
        id = 'DHEXrGV',
        name = "Demonic Speed",
        desc = [[HFD WUT EX rGV DH mods]],
        quote = [[Prove your hellish capabilities to the world.]],
        credit = "@GameTilDead",
        rank = floorRank(1, 3, 5, 7, 9, 10, 4200),
        hide = function() return GAME.completion.GV == 0 end,
    },
    { -- rASrGV
        ex = true,
        id = 'rASrGV',
        name = "Whizzing Wizard",
        desc = [[HFD WUT rGV rAS mods]],
        quote = [["I felt enchanted!"  But soon after, disaster struck...]],
        credit = "@GameTilDead",
        rank = floorRank(1, 3, 5, 7, 9, 10, 4200),
        hide = function() return GAME.completion.GV == 0 or GAME.completion.AS == 0 end,
    },
    { -- rGVrIN
        id = 'rGVrIN',
        name = "The Grandmaster+",
        desc = [[HFD WUT rGV rIN mods]],
        quote = [[Even when the universe collapsed, the real grandmaster still remains at peace.]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 2600),
        hide = function() return GAME.completion.GV == 0 or GAME.completion.IN == 0 end,
    },
    { -- NHrAS
        ex = true,
        id = 'NHrAS',
        name = "Pristine",
        desc = [[HFD WUT NH rAS mods]],
        quote = [[The pearl of your gameplay requires perfection for a clean finish.]],
        credit = "@GameTilDead",
        rank = floorRank(1, 3, 5, 7, 9, 10, 2600),
        hide = function() return GAME.completion.AS == 0 end,
    },
    { -- rASrDH
        ex = true,
        id = 'GVrASrDH',
        name = "Storage Overload",
        desc = [[HFD WUT GV rDH rAS mods]],
        quote = [[Believe it or not, you don't have to memorize every one.]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 2600),
        hide = function() return GAME.completion.DH == 0 or GAME.completion.AS == 0 end,
    },
    { -- DHNHrASrIN
        ex = true,
        id = 'DHNHrASrIN',
        name = "Steganography",
        desc = [[HFD WUT NH DH rIN rAS mods]],
        quote = [[Sometimes, the best hiding place is in plain sight.]],
        credit = "@obsidian",
        rank = floorRank(1, 3, 5, 7, 9, 10, 2600),
        hide = function() return GAME.completion.IN == 0 or GAME.completion.AS == 0 end,
    },
    { -- DHrMSrNH
        ex = true,
        id = 'DHrMSrNH',
        name = "Deadbeat",
        desc = [[HFD WUT rNH rMS DH mods]],
        quote = [[Hated and despised, and yet they struggle on.]],
        credit = "@Tizago",
        rank = floorRank(1, 3, 5, 7, 9, 10, 2200),
        hide = function() return GAME.completion.NH == 0 or GAME.completion.MS == 0 end,
    },
    { -- rGVrNHrVL
        ex = true,
        id = 'rGVrNHrVL',
        name = "Sweatshop",
        desc = [[HFD WUT rNH rGV rVL mods]],
        quote = [[Carefree life is not for the asking, someone else is carrying the burden for you.]],
        credit = "@obsidian",
        rank = floorRank(1, 3, 5, 7, 9, 10, 2200),
        hide = function() return GAME.completion.NH == 0 or GAME.completion.GV == 0 or GAME.completion.VL == 0 end,
    },
    { -- DHGVNHrMS
        ex = true,
        id = 'DHGVNHrMS',
        name = "Trench Warfare",
        desc = [[HFD WUT NH rMS GV DH mods]],
        quote = [[Dig deep, move fast, and keep your head low.]],
        credit = "@Tizago",
        rank = floorRank(1, 3, 5, 7, 9, 10, 2200),
        hide = function() return GAME.completion.MS == 0 end,
    },
    { -- DPGVMSrNH
        ex = true,
        id = 'DPGVMSrNH',
        name = "Grand-Master! Rounds",
        desc = [[HFD WUT rNH MS GV DP mods]],
        quote = [[YOUR AER: GRAND-MASTER! Rounds]],
        -- credit = "TGM4",
        rank = floorRank(1, 3, 5, 7, 9, 10, 2000),
        hide = function() return GAME.completion.NH == 0 end,
    },
    { -- rINrNH
        ex = true,
        id = 'rINrNH',
        name = "Instant Memory",
        desc = [[HFD WUT rNH rIN mods]],
        quote = [[In the twinkling of a eye.]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 2000),
        hide = function() return GAME.completion.NH == 0 or GAME.completion.IN == 0 end,
    },
    { -- EXGVNHrMS
        ex = true,
        id = 'EXGVNHrMS',
        name = "Bnuuy",
        desc = [[HFD WUT EX NH rMS GV mods]],
        quote = [[Look at them hopping around! Too bad they don't want to be picked up...]],
        credit = "@GameTilDead",
        rank = floorRank(1, 3, 5, 7, 9, 10, 2000),
        hide = function() return GAME.completion.MS == 0 end,
    },
    { -- DHrEXrVL
        ex = true,
        id = 'DHrEXrVL',
        name = "Sweat and Ruin",
        desc = [[HFD WUT rEX rVL DH mods]],
        quote = [[Putting your blood, sweat, and tears to the climb, or fall.]],
        credit = "@Tizago",
        rank = floorRank(1, 3, 5, 6, 7, 8, 9),
        hide = function() return GAME.completion.EX == 0 end,
    },
    { -- MSrDPrGV
        ex = true,
        id = 'MSrDPrGV',
        name = "Rushed Relationship",
        desc = [[HFD WUT MS rGV rDP mods]],
        quote = [["Can we please talk about this first?!"]],
        credit = "@GameTilDead",
        rank = floorRank(1, 3, 4, 5, 6, 7, 9),
        hide = function() return GAME.completion.GV == 0 or GAME.completion.DP == 0 end,
    },
    { -- rDPrEX
        ex = true,
        id = 'rDPrEX',
        name = "Tyrannical Dyarchy",
        desc = [[HFD WUT rEX rDP mods]],
        quote = [[Live in fear and despair.]],
        rank = floorRank(1, 2, 3, 4, 6, 7, 8),
        hide = function() return GAME.completion.EX == 0 or GAME.completion.DP == 0 end,
    },
    { -- INMSrDHrEX
        ex = true,
        id = 'INMSrDHrEX',
        name = "Sisyphean Monarchy",
        desc = [[HFD WUT rEX MS rDH IN mods]],
        quote = [[Ruling an unruly empire on the brink of collapse.]],
        credit = "@Syakegohan",
        rank = floorRank(1, 2, 3, 4, 6, 7, 8),
        hide = function() return GAME.completion.EX == 0 or GAME.completion.DH == 0 end,
    },
    { -- VLrDPrIN
        ex = true,
        id = 'VLrDPrIN',
        name = "Painful Relapse",
        desc = [[HFD WUT VL rIN rDP mods]],
        quote = [["I miss my ex..."]],
        credit = "@obsidian",
        rank = floorRank(1, 2, 3, 4, 5, 6, 7),
        hide = function() return GAME.completion.IN == 0 or GAME.completion.DP == 0 end,
    },
    { -- rDHrIN
        ex = true,
        id = 'rDHrIN',
        name = "Brain Capacity",
        desc = [[HFD WUT rDH rIN mods]],
        quote = [[How long can you keep up in this forsaken memory game?]],
        credit = "@GameTilDead",
        rank = floorRank(1, 1, 2, 3, 4, 5, 6),
        hide = function() return GAME.completion.DH == 0 or GAME.completion.IN == 0 end,
    },
    { -- swamp_water_lite_plus
        ex = true,
        id = 'swamp_water_lite_plus',
        name = "Swamp Water Lite+",
        desc = [[HFD WUT 1rev+6 mods ("Duo" not allowed)]],
        quote = [[Comes in...... 252 different flavors?]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 2200),
        hide = function() return TABLE.countAll(GAME.completion, 0) == 9 end,
    },
    { -- swamp_water_plus
        ex = true,
        id = 'swamp_water_plus',
        name = "Swamp Water+",
        desc = [[HFD WUT 1rev+7 mods ("Duo" not allowed)]],
        quote = [[Less choices but still a lot to try.]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 2000),
        hide = function() return TABLE.countAll(GAME.completion, 0) == 9 end,
    },
    { -- swamp_water_pro_plus
        ex = true,
        id = 'swamp_water_pro_plus',
        name = "Swamp Water Pro+",
        desc = [[HFD WUT 1rev+8 mods]],
        quote = [[The cup is about to overflow!]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 1800),
        hide = function() return TABLE.countAll(GAME.completion, 0) == 9 end,
    },

    { title = "Why", hide = function() return TABLE.countAll(GAME.completion, 0) >= 8 end },
    {},
    { -- blight
        ex = true,
        id = 'blight',
        name = "Blight",
        desc = [[HFD with 8+ mod points]],
        quote = [[The world starts withering...]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 4200),
        hide = function() return TABLE.countAll(GAME.completion, 0) > 7 end,
    },
    { -- desolation
        ex = true,
        id = 'desolation',
        name = "Desolation",
        desc = [[HFD with 9+ mod points]],
        quote = [[Vitality has faded from the world's palette...]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 2600),
        hide = function() return TABLE.countAll(GAME.completion, 0) > 7 end,
    },
    { -- havoc
        ex = true,
        id = 'havoc',
        name = "Havoc",
        desc = [[HFD with 10+ mod points]],
        quote = [[The world is in chaos...]],
        rank = floorRank(1, 3, 5, 7, 8, 9, 10),
        hide = function() return TABLE.countAll(GAME.completion, 0) > 7 end,
    },
    { -- pandemonium
        ex = true,
        id = 'pandemonium',
        name = "Pandemonium",
        desc = [[HFD with 11+ mod points]],
        quote = [[Several realms began to collide...]],
        rank = floorRank(1, 2, 4, 6, 8, 9, 10),
        hide = function() return TABLE.countAll(GAME.completion, 0) > 7 end,
    },
    { -- inferno
        ex = true,
        id = 'inferno',
        name = "Inferno",
        desc = [[HFD with 12+ mod points]],
        quote = [[Everything is burning and melting...]],
        rank = floorRank(1, 2, 4, 6, 7, 8, 9),
        hide = function() return TABLE.countAll(GAME.completion, 0) > 6 end,
    },
    { -- purgatory
        ex = true,
        id = 'purgatory',
        name = "Purgatory",
        desc = [[HFD with 13+ mod points]],
        quote = [[Nobody knows their destination...]],
        rank = floorRank(1, 1, 3, 5, 6, 7, 8),
        hide = function() return TABLE.countAll(GAME.completion, 0) > 5 end,
    },
    { -- perdition
        ex = true,
        id = 'perdition',
        name = "Perdition",
        desc = [[HFD with 14+ mod points]],
        quote = [[There's no way back...]],
        rank = floorRank(1, 1, 3, 4, 5, 6, 7),
        hide = function() return TABLE.countAll(GAME.completion, 0) > 4 end,
    },
    { -- cataclysm
        ex = true,
        id = 'cataclysm',
        name = "Cataclysm",
        desc = [[HFD with 15+ mod points]],
        quote = [[The real disaster is yet to come...]],
        rank = floorRank(1, 1, 2, 3, 4, 5, 6),
        hide = function() return TABLE.countAll(GAME.completion, 0) > 3 end,
    },
    { -- annihilation
        ex = true,
        id = 'annihilation',
        name = "Annihilation",
        desc = [[HFD with 16+ mod points]],
        quote = [[The whole universe is trembling...]],
        rank = floorRank(1, 1, 1, 2, 3, 4, 5),
        hide = function() return TABLE.countAll(GAME.completion, 0) > 2 end,
    },
    { -- armageddon
        ex = true,
        id = 'armageddon',
        name = "Armageddon",
        desc = [[HFD with 17+ mod points]],
        quote = [[The Big Crunch is about to happen...]],
        rank = floorRank(1, 1, 1, 1, 2, 3, 4),
        hide = function() return TABLE.countAll(GAME.completion, 0) > 1 end,
    },
    { -- abyss
        ex = true,
        id = 'abyss',
        name = "Abyss",
        desc = [[HFD with 18 mod points]],
        quote = [[.]],
        rank = floorRank(1, 1, 1, 1, 1, 2, 3),
        hide = function() return TABLE.countAll(GAME.completion, 0) > 0 end,
    },
    {},

    { title = "Special" },
    {},
    { -- the_escape_artist
        id = 'the_escape_artist',
        name = "The Escape Artist",
        desc = [[Quests passed with wound triggered WUT "Double Hole Garbage", "Messier Garbage" and "All-Spin" mods]],
        quote = [["An impossible situation! A daring illusionist! Will he make it out alive?"]],
        rank = numberRank(0, 10, 26, 50, 70, 90, 126),
        scoreSimp = function(quest) return floor(quest) .. " Quests" end,
    },
    { -- talentless
        id = 'talentless',
        name = "Talentless",
        desc = [[HFD WUT "All-Spin" mod without using keyboard]],
        quote = [[Reaching deep down but coming back empty every time.]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 4200),
    },
    { -- block_rationing
        id = 'block_rationing',
        name = "Block Rationing",
        desc = [[Highest altitude on 40 quests WUT "Expert Mode" and "Messier Garbage" mods]],
        quote = [[Adversity favors the resourceful.]],
        scoreSimp = heightNumber,
        rank = numberRank(0, 260, 360, 450, 495, 550, 600),
    },
    { -- the_responsible_one
        id = 'the_responsible_one',
        name = "The Responsible One",
        desc = [[Highest amount of revivals performed in a single duo run]],
        quote = [["Could you please stop dying?"]],
        scoreSimp = function(revive) return revive .. " Revives" end,
        rank = numberRank(0, 3, 6, 9, 12, 14, 16),
    },
    { -- guardian_angel
        id = 'guardian_angel',
        name = "Guardian Angel",
        desc = [[Highest altitude to perform a successful revive at]],
        quote = [[An angel's intervention.]],
        scoreSimp = heightNumber,
        rank = numberRank(0, 626, 942, 1620, 2000, 2600, 4200),
    },
    { -- lovers_promise
        id = 'lovers_promise',
        name = "Lover's Promise",
        desc = [[Highest altitude reached with DP on 14th day of a month (No CR)]],
        quote = [[The impossible promise of an eternity just like this moment.]],
        scoreSimp = heightNumber,
        type = 'event',
    },
    { -- moon_struck
        ex = true,
        id = 'moon_struck',
        name = "Moon Struck",
        desc = [[Finish the run at exactly 2202.8m (±3/±1/±0)]],
        quote = [[TODO]],
        scoreSimp = heightNumber,
        credit = "@osk",
        notUsed = true,
    },
    { -- clutch_main
        ex = true,
        id = 'clutch_main',
        name = "Clutch Main",
        desc = [[Quests passed while HP in danger, WUT NH rGV mods]],
        quote = [[Your horses had better be held onto!]],
        credit = "@GameTilDead",
        rank = numberRank(0, 26, 42, 62, 94, 126, 180),
        scoreSimp = function(quest) return floor(quest) .. " Quests" end,
        hide = function() return GAME.completion.GV == 0 end,
    },
    { -- powerless
        ex = true,
        id = 'powerless',
        name = "Powerless",
        desc = [[HFD without building up surge]],
        quote = [["We have a similar goal to climb the Zenith Tower in many ways."]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 4200),
    },
    { -- the_pacifist
        ex = true,
        id = 'the_pacifist',
        name = "The Pacifist",
        desc = [[Minimum attack before reaching F10]],
        quote = [[Give evil nothing to oppose and it will disappear by itself.]],
        credit = "@wah",
        comp = '<',
        rank = numberRankRev(500, 426, 412, 400, 395, 390, 380),
        scoreSimp = function(atk) return atk .. " Attack" end,
    },
    { -- divine_rejection
        ex = true,
        id = 'divine_rejection',
        name = "Divine Rejection",
        desc = [[Finish the run exactly before F10]],
        quote = [["And in the end, it doesn't even matter..."]],
        rank = numberRank(1626, 1626, 1635, 1640, 1645, 1647.8, 1649),
        scoreSimp = function(h) return string.format("%.2fm", h) end,
    },
    { -- sunk_cost
        ex = true,
        id = 'sunk_cost',
        name = "Sunk Cost",
        desc = [[HFD without losing rank]],
        quote = [["Cross the line, and the descent begins."]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 2600),
    },
    { -- knife_edge
        ex = true,
        id = 'knife_edge',
        name = "Knife-edge",
        desc = [[HFD without losing rank, with at least EX]],
        quote = [[A delicate dance on the cutting edge.]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 2000),
    },
    { -- carried
        ex = true,
        id = 'carried',
        name = "Carried",
        desc = [[HFD with only one player alive, with at least DP]],
        quote = [["I have no idea how to play the game, can you unlock the mods for me?"]],
        credit = "@obsidian",
        rank = floorRank(1, 3, 5, 7, 9, 10, 2000),
    },
    { -- patience_is_a_virtue
        ex = true,
        id = 'patience_is_a_virtue',
        name = "Patience is a Virtue",
        desc = [[HFD without manually commit]],
        quote = [[Opportunities always favor those who are prepared and wait.]],
        credit = "@The_111thBlitzer",
        rank = floorRank(1, 3, 5, 7, 9, 10, 2200),
    },
    { -- fel_magic
        ex = true,
        id = 'fel_magic',
        name = "Fel Magic",
        desc = [[Quests passed with wound triggered during GIGASPEED, with rAS]],
        quote = [["And what, Gul'dan, must we give it return?"]],
        -- credit = "WoW",
        rank = numberRank(0, 6, 15, 26, 42, 62, 100),
        scoreSimp = function(quest) return floor(quest) .. " Quests" end,
        hide = function() return GAME.completion.AS == 0 or STAT.totalGiga == 0 end,
    },
    { -- arrogance
        ex = true,
        id = 'arrogance',
        name = "Arrogance",
        desc = [[HFD with rAS and no perfect pass]],
        quote = [[Maintaining arrogance constantly is also not easy.]],
        rank = floorRank(1, 1, 1, 1, 2, 3, 4),
        hide = function() return GAME.completion.AS == 0 end,
    },
    { -- honeymoon
        ex = true,
        id = 'honeymoon',
        name = "Honeymoon",
        desc = [[HFD with every commit shares at least one mod with previous, with at least (r)DP]],
        quote = [["Can we be together forever?"]],
        rank = floorRank(1, 2, 3, 4, 7, 9, 2000),
    },
    { -- break_up
        ex = true,
        id = 'break_up',
        name = "Break Up",
        desc = [[HFD without commiting any mod twice in a row, with at least (r)DP]],
        quote = [["Never let me see you again."]],
        rank = floorRank(1, 3, 5, 6, 7, 8, 9),
    },
    { -- the_unreliable_one
        ex = true,
        id = 'the_unreliable_one',
        name = "The Unreliable One",
        desc = [[Highest amount of KILLs performed in a single reversed duo run]],
        quote = [["I won't stop killling."]],
        scoreSimp = function(kill) return kill .. " Kills" end,
        rank = numberRank(0, 2, 3, 4, 5, 7, 10),
        hide = function() return GAME.completion.DP == 0 end,
    },
    { -- detail_oriented
        id = 'detail_oriented',
        name = "Detail Oriented",
        desc = [[Reach F10 with the fewest flips]],
        quote = [[Theoretically efficient can quickly become gloriously impractical.]],
        comp = '<',
        rank = numberRankRev(260, 240, 220, 200, 180, 150, 100),
        scoreSimp = function(flip) return floor(flip) .. " Flips" end,
    },
    { -- psychokinesis
        ex = true,
        id = 'psychokinesis',
        name = "Psychokinesis",
        desc = [[HFD with 0 flip in the result]],
        quote = [[Real magic exists!]],
        rank = floorRank(1, 1, 1, 1, 2, 3, 5),
    },
    {},

    { title = "Supercharged Clone", credit = "@Garbo" },
    {},
    { -- museum_heist
        ex = true,
        id = 'museum_heist',
        name = "Museum Heist",
        desc = [[Shortest time spent in F5 with DH DP]],
        quote = [[Less time, less evidence.]],
        credit = "@Baron",
        comp = '<',
        scoreSimp = function(time) return string.format("%.2fs", time) end,
        rank = numberRankRev(35, 26, 20, 12, 6.2, 4.2, 2.6),
    },
    { -- ultra_dash
        ex = true,
        id = 'ultra_dash',
        name = "Ultra Dash",
        desc = [[Shortest time spent in F9]],
        quote = [[Probably a good strategy for speedrunning 1.2x faster.]],
        comp = '<',
        scoreSimp = function(time) return string.format("%.2fs", time) end,
        rank = numberRankRev(62, 26, 16, 12, 6.2, 2.6, 1.0),
    },
    { -- perfect_speedrun
        ex = true,
        id = 'perfect_speedrun',
        name = "Perfect Speedrun",
        desc = [[Reach 75 Back-to-Back as fast as possible]],
        quote = [[Supercharged B75%]],
        comp = '<',
        scoreSimp = function(time) return string.format("%.2fs", time) end,
        rank = numberRankRev(150, 115, 90, 70, 55, 45, 40),
    },
    { -- the_perfectionist
        ex = true,
        id = 'the_perfectionist',
        name = "The Perfectionist",
        desc = [[HFD with no imperfect pass or getting hurt]],
        quote = [[Supercharged Perf%]],
        rank = floorRank(1, 3, 5, 7, 9, 10, 2600),
    },
    { -- teraspeed
        ex = true,
        id = 'teraspeed',
        name = "TeraSpeed",
        desc = [[Highest rank reached]],
        quote = [[Chasing for the ultimate speed, with all else cast aside.]],
        rank = numberRank(12, 14, 15, 16, 17, 18, 20),
        scoreSimp = function(rank) return "Rank " .. rank end,
    },
    { -- stable_rise
        ex = true,
        id = 'stable_rise',
        name = "Stable Rise",
        desc = [[Highest rank stayed at least 1 min in one run]],
        quote = [[Speed is the key, but the real challenge is to hold it.]],
        rank = numberRank(9, 11, 13, 14, 15, 16, 18),
        scoreSimp = function(rank) return "Rank " .. (rank == 26 and "26 (Max)" or rank) end,
    },
    { -- the_spike_of_nomod_time
        ex = true,
        id = 'the_spike_of_nomod_time',
        name = "The Spike of Nomod Time",
        desc = [[Largest spike sent without any mods]],
        quote = [[Some climbers put their faith solely on divine power; not daring to ask for more.]],
        rank = numberRank(0, 26, 42, 70, 94, 126, 196),
        scoreSimp = function(spike) return floor(spike) .. " Spike" end,
    },
    { -- the_spike_of_all_time_plus
        ex = true,
        id = 'the_spike_of_all_time_plus',
        name = "The Spike of All Time+",
        desc = [[Largest spike sent]],
        quote = [[While some climbers also attempt to rewrite their destiny on power from outside.]],
        rank = numberRank(0, 10, 26, 42, 62, 126, 200),
        scoreSimp = function(spike) return floor(spike) .. " Spike" end,
    },

    { title = "Issued (No CR)" },
    {},
    { -- identity
        ex = true,
        id = 'identity',
        name = "Identity",
        desc = [[Change ID or about-me]],
        quote = [[Is this free?]],
        type = 'issued',
    },
    { -- respectful
        ex = true,
        id = 'respectful',
        name = "Respectful",
        desc = [[Stay in ABOUT page for 26s]],
        quote = [[Press F2 to pay respect]],
        -- credit = "COD11",
        type = 'issued',
    },
    { -- zenith_relocation
        ex = true,
        id = 'zenith_relocation',
        name = "Zenith Relocation",
        desc = [[Export your save to a different platform (Web / Windows / Linux)]],
        quote = [[Uncover the mysteries of a new, familiar Tower.]],
        credit = "@GameTilDead",
        type = 'issued',
    },
    { -- intended_glitch
        ex = true,
        id = 'intended_glitch',
        name = "Intended Glitch",
        desc = [[Play Duo]],
        quote = [[The heart's lock yields to the artful understanding of spin.]],
        type = 'issued',
    },
    { -- skys_the_limit
        ex = true,
        id = 'skys_the_limit',
        name = "Sky's The Limit",
        desc = [[Reach 6200m]],
        quote = [[Edge of the universe.]],
        type = 'issued',
    },
    { -- superluminal
        ex = true,
        id = 'superluminal',
        name = "Superluminal",
        desc = [[Reach F10 in 76.2s]],
        quote = [[Faster than light!]],
        type = 'issued',
    },
    { -- the_harbinger
        id = 'the_harbinger',
        name = "The Harbinger",
        desc = [[Reach floor 5 in all nine reversed mods]],
        quote = [[Weathering the storm of an unfavorable future.]],
        hide = TRUE,
        type = 'issued',
    },
    { -- dark_force
        ex = true,
        id = 'dark_force',
        name = "Dark Force",
        desc = [[Interrupt font loading with rev mod]],
        quote = [[The darkness overflows.]],
        hide = TRUE,
        type = 'issued',
    },
    { -- speedrun_speedrunning
        ex = true,
        id = 'speedrun_speedrunning',
        name = "Speedrun Speedrunning",
        desc = [[Enter GIGASPEED on F1]],
        quote = [[Not much of a speedrun]],
        type = 'issued',
        hide = function() return STAT.totalGiga == 0 end,
    },
    { -- worn_out
        ex = true,
        id = 'worn_out',
        name = "Worn Out",
        desc = [[Reach f10 with GIGASPEED after retaining it for 5 minutes]],
        quote = [[You alright over there? You seem a bit tired from all that "speed"-running...]],
        credit = "@GameTilDead",
        type = 'issued',
        hide = function() return STAT.totalGiga == 0 end,
    },
    { -- mastery
        ex = true,
        id = 'mastery',
        name = "Mastery",
        desc = [[Mastery on all single mods]],
        quote = [[Game cleared, congratulations!]],
        type = 'issued',
    },
    { -- terminal_velocity
        ex = true,
        id = 'terminal_velocity',
        name = "Terminal Velocity",
        desc = [[Speedrun all single mods]],
        quote = [[Reaching for the stars again and again.]],
        credit = "@The_111thBlitzer",
        hide = function() return STAT.totalGiga == 0 end,
        type = 'issued',
    },
    { -- final_defiance
        ex = true,
        id = 'final_defiance',
        name = "Final Defiance",
        desc = [[Meet the final fatigue effect]],
        quote = [["This is not the end!"]],
        credit = "@Flowerling",
        type = 'issued',
    },
    { -- royal_resistance
        ex = true,
        id = 'royal_resistance',
        name = "Royal Resistance",
        desc = [[Meet the final fatigue effect with rEX]],
        quote = [["History will prove me right!!"]],
        credit = "@Flowerling",
        hide = function() return GAME.completion.EX == 0 end,
        type = 'issued',
    },
    { -- lovers_stand
        ex = true,
        id = 'lovers_stand',
        name = "Lover's Stand",
        desc = [[Meet the final fatigue effect with rDP]],
        quote = [[The power of affection sees you through the bitter end.]],
        hide = function() return GAME.completion.DP == 0 end,
        type = 'issued',
    },
    { -- and_then_nothing
        ex = true,
        id = 'and_then_nothing',
        name = "And Then... Nothing",
        desc = [[Survive after breaking B2B x 50 while using rDP and one player is KO'd]],
        quote = [[Moral of the story: NEVER exploit your partner.]],
        credit = "@GameTilDead",
        hide = function() return GAME.completion.DP == 0 end,
        type = 'issued',
    },
    { -- fruitless_effort
        ex = true,
        id = 'fruitless_effort',
        name = "Fruitless Effort",
        desc = [[Finish a game with bonus over 260%]],
        quote = [[Effort is pointless if you are not strong enough.]],
        hide = function() return GAME.completion.EX == 0 end,
        type = 'issued',
    },
    { -- false_god
        ex = true,
        id = 'false_god',
        name = "False God",
        desc = [[Mastery on all mods]],
        quote = [[Do it again but without clever tricks this time.]],
        type = 'issued',
        hide = TRUE,
    },
    { -- supremacy
        ex = true,
        id = 'supremacy',
        name = "Supremacy",
        desc = [[Mastery on all single rev mods]],
        quote = [[Your reign has begun, and it knows no end.]],
        type = 'issued',
        hide = TRUE,
    },
    { -- the_completionist
        ex = true,
        id = 'the_completionist',
        name = "The Completionist",
        desc = [[Speedrun all single rev mods]],
        quote = [[The full spectrum of the mods now lies within your grasp.]],
        type = 'issued',
        hide = TRUE,
    },
    { -- zenith_traveler
        ex = true,
        id = 'zenith_traveler',
        name = "Zenith Traveler",
        desc = [[Enter traveler mode]],
        quote = [[Also known as background debugging mode]],
        type = 'issued',
    },
    { -- somersault
        ex = true,
        id = 'somersault',
        name = "Somersault",
        desc = [[Reversing card animation ended at non-rev activated state]],
        quote = [[Elegant backflip]],
        hide = TRUE,
        type = 'issued',
    },
    { -- its_kinda_rare
        id = 'its_kinda_rare',
        name = "It's Kinda Rare!",
        desc = [[Master the daily combo including 2 reversed mods.]],
        quote = [[Those who are capable and also fortunate deserve a lifetime reward.]],
        credit = "@GameTilDead",
        rank = numberRank(0, 0, 0, 1, 2, 4, 6),
        scoreSimp = function(day) return day == 1 and "1 Day" or day .. " Days" end,
        hide = TRUE,
        type = 'issued',
    },
}

local compFunc = {
    ['>'] = function(a, b) return a - b > 1e-10 end,
    ['<'] = function(a, b) return b - a > 1e-10 end,
}
local defaultFloorRank = floorRank(1, 3, 5, 7, 9, 10, 6200)

TABLE.foreach(Achievements, function(v) return v.notUsed end, true)

for i = 1, #Achievements do
    local achv = Achievements[i]
    local id = achv.id
    if id then
        Achievements[id] = achv

        assert(type(id) == 'string', "Missing field 'name' - " .. id)
        assert(type(achv.name) == 'string', "Missing field 'name' - " .. id)

        assert(achv.desc, "Missing field 'desc' - " .. id)
        achv.desc = achv.desc
            :gsub("WUT", "while using the")
            :gsub("HFD", "Highest floor discovered")

        assert(achv.quote, "Missing field 'quote' - " .. id)

        achv.credit = achv.credit or ""

        if achv.comp == nil then
            achv.comp = compFunc['>']
        elseif compFunc[achv.comp] then
            achv.comp = compFunc[achv.comp]
            if achv.comp == '<' then achv.noScore = 26000 end
        elseif type(achv.comp) ~= 'function' then
            error("Invalid field 'comp' - " .. id)
        end

        if achv.rank == nil then achv.rank = defaultFloorRank end
        assert(type(achv.rank) == 'function', "Invalid field 'rank' - " .. id)

        if achv.scoreSimp == nil then
            achv.scoreSimp = heightFloor
            achv.scoreFull = heightNumber
        end
        assert(type(achv.scoreSimp) == 'function', "Invalid field 'scoreSimp' - " .. id)
        assert(achv.scoreFull == nil or type(achv.scoreFull) == 'function', "Invalid field 'scoreFull' - " .. id)

        if achv.type == nil then achv.type = 'competitive' end
        assert(type(achv.type) == 'string', "Invalid field 'type' - " .. id)
    end
    achv.hide = achv.hide or FALSE
end
