return {
    -------- EX NH MS GV VL DH IN AS 2P --------
    { set = '   NH    GV               ', name = "a modern classic",          basic = true },
    { set = '   NH MS       DH         ', name = "deadlock",                  basic = true },
    { set = '      MS       DH    AS   ', name = "the escape artist",         basic = true },
    { set = '         GV       IN      ', name = "the grandmaster",           basic = true },
    { set = 'EX NH          DH         ', name = "emperor's decadence",       basic = true },
    { set = 'EX    MS    VL DH         ', name = "divine mastery",            basic = true },
    { set = '   NH                AS   ', name = "the starving artist",       basic = true },
    { set = 'EX          VL       AS   ', name = "the con artist",            basic = true },
    { set = '                        2P', name = "trained profesionals",      basic = true },

    { set = '      MS          IN      ', name = "scrambled rainbow" },
    { set = 'EX NH                AS   ', name = "positioning master" },

    -- Contents below are ideas from tetr.io's community:
    -- https://docs.google.com/spreadsheets/d/1syh3q2oiduCZb1cJ5QI95Y2XhhedAfhv4YnEH9z2tbc
    { set = '                  IN AS   ', name = "the abstract artist" },
    { set = '               DH    AS   ', name = "the deal with the devil" },
    { set = '               DH IN      ', name = "the ghost" },
    { set = '               DH IN AS   ', name = "the libertine" },
    { set = '            VL       AS   ', name = "water from stone" },
    { set = '            VL    IN      ', name = "ruthlessness" },
    { set = '            VL    IN AS   ', name = "eccentric recluse" },
    { set = '            VL DH         ', name = "lucifier" },
    { set = '            VL DH    AS   ', name = "forbidden sorcery" },
    { set = '            VL DH IN      ', name = "chasm" },
    { set = '         GV          AS   ', name = "the juggler" },
    { set = '         GV       IN      ', name = "the grandmaster" },
    { set = '         GV       IN AS   ', name = "the spinmaster" },
    { set = '         GV    DH         ', name = "the speed demon" },
    { set = '         GV    DH    AS   ', name = "the texting driver" },
    { set = '         GV    DH IN      ', name = "the drunk driver" },
    { set = '         GV VL            ', name = "comfort food" },
    { set = '         GV VL       AS   ', name = "the gladiator" },
    { set = '         GV VL    IN      ', name = "connection issues" },
    { set = '         GV VL    IN AS   ', name = "immense pressure" },
    { set = '         GV VL DH         ', name = "temptation" },
    { set = '         GV VL DH IN      ', name = "nightmare" },
    { set = '      MS             AS   ', name = "roulette wheel" },
    { set = '      MS          IN      ', name = "blind bet" },
    { set = '      MS       DH         ', name = "messy double hole" },
    { set = '      MS       DH    AS   ', name = "the escape artist" },
    { set = '      MS       DH IN      ', name = "the stealth ninja" },
    { set = '      MS       DH IN AS   ', name = "nascent" },
    { set = '      MS    VL            ', name = "swiss cheese" },
    { set = '      MS    VL       AS   ', name = "cream cheese" },
    { set = '      MS    VL    IN      ', name = "starstruck" },
    { set = '      MS    VL DH         ', name = "utter trash" },
    { set = '      MS    VL DH    AS   ', name = "blue cheese" },
    { set = '      MS    VL DH IN      ', name = "the night watchman" },
    { set = '      MS GV               ', name = "cheese race" },
    { set = '      MS GV          AS   ', name = "rough sketch" },
    { set = '      MS GV    DH         ', name = "double down" },
    { set = '      MS GV VL            ', name = "survival" },
    { set = '      MS GV VL    IN AS   ', name = "mortal chaos" },
    { set = '      MS GV VL DH         ', name = "quadruple down" },
    { set = '      MS GV VL DH    AS   ', name = "killer clown" },
    { set = '      MS GV VL DH IN      ', name = "slaughterhouse" },
    { set = '   NH                AS   ', name = "the starving artist" },
    { set = '   NH             IN      ', name = "helen keller" },
    { set = '   NH             IN AS   ', name = "the blind artist" },
    { set = '   NH          DH         ', name = "purgatory" },
    { set = '   NH          DH    AS   ', name = "shapeshifter" },
    { set = '   NH          DH IN      ', name = "blindside" },
    { set = '   NH       VL            ', name = "resistance" },
    { set = '   NH       VL    IN      ', name = "justice" },
    { set = '   NH       VL DH         ', name = "judgment" },
    { set = '   NH       VL DH    AS   ', name = "the street artist" },
    { set = '   NH    GV               ', name = "a modern classic" },
    { set = '   NH    GV          AS   ', name = "a modern twist" },
    { set = '   NH    GV       IN      ', name = "evanescence" },
    { set = '   NH    GV       IN AS   ', name = "divine failure" },
    { set = '   NH    GV    DH         ', name = "damnation" },
    { set = '   NH    GV    DH    AS   ', name = "backbar" },
    { set = '   NH    GV    DH IN AS   ', name = "cheat code" },
    { set = '   NH    GV VL            ', name = "trational" },
    { set = '   NH    GV VL    IN      ', name = "the black hole" },
    { set = '   NH    GV VL DH         ', name = "nephalem" },
    { set = '   NH    GV VL DH    AS   ', name = "demonic possesion" },
    { set = '   NH MS                  ', name = "all in" },
    { set = '   NH MS       DH         ', name = "deadlock" },
    { set = '   NH MS       DH    AS   ', name = "locksmith" },
    { set = '   NH MS       DH IN      ', name = "unfinished business" },
    { set = '   NH MS       DH IN AS   ', name = "disappearance" },
    { set = '   NH MS    VL    IN      ', name = "drowned" },
    { set = '   NH MS    VL DH         ', name = "deadbolt" },
    { set = '   NH MS    VL DH IN      ', name = "blind faith" },
    { set = '   NH MS GV               ', name = "atlas' burden" },
    { set = '   NH MS GV    DH         ', name = "futile struggle" },
    { set = '   NH MS GV    DH IN      ', name = "misdrop haven" },
    { set = '   NH MS GV VL            ', name = "quadruple threat" },
    { set = '   NH MS GV VL DH         ', name = "quintuple threat" },
    { set = 'EX                   AS   ', name = "dancing queen" },
    { set = 'EX                IN      ', name = "emperor's dilemma" },
    { set = 'EX                IN AS   ', name = "expertise" },
    { set = 'EX             DH         ', name = "the devil's temptation" },
    { set = 'EX             DH    AS   ', name = "loki" },
    { set = 'EX             DH IN AS   ', name = "reverse quadruple threat" },
    { set = 'EX          VL            ', name = "icarus" },
    { set = 'EX          VL       AS   ', name = "the con artist" },
    { set = 'EX          VL    IN      ', name = "bounty hunter" },
    { set = 'EX          VL    IN AS   ', name = "insanity" },
    { set = 'EX          VL DH         ', name = "the mad lord" },
    { set = 'EX          VL DH IN      ', name = "corruption" },
    { set = 'EX          VL DH IN AS   ', name = "reverse quintuple threat" },
    { set = 'EX       GV               ', name = "inviticus" },
    { set = 'EX       GV          AS   ', name = "master of the t" },
    { set = 'EX       GV       IN      ', name = "the super gm (grandmaster)" },
    { set = 'EX       GV       IN AS   ', name = "mastermind" },
    { set = 'EX       GV    DH         ', name = "the daredevil" },
    { set = 'EX       GV VL            ', name = "relaxation" },
    { set = 'EX       GV VL       AS   ', name = "enirsia " },
    { set = 'EX       GV VL    IN      ', name = "lateness" },
    { set = 'EX       GV VL    IN AS   ', name = "speed the collapse" },
    { set = 'EX    MS                  ', name = "rational reasoning" },
    { set = 'EX    MS             AS   ', name = "the rich gambler" },
    { set = 'EX    MS          IN AS   ', name = "the mathematician" },
    { set = 'EX    MS    VL            ', name = "the wolf of wall street" },
    { set = 'EX    MS    VL       AS   ', name = "the hacker" },
    { set = 'EX    MS    VL    IN AS   ', name = "reload" },
    { set = 'EX    MS    VL DH         ', name = "divine mastery" },
    { set = 'EX    MS    VL DH    AS   ', name = "false security" },
    { set = 'EX    MS GV               ', name = "mining operation" },
    { set = 'EX    MS GV    DH         ', name = "mining for netherite" },
    { set = 'EX    MS GV VL            ', name = "juggernaut" },
    { set = 'EX    MS GV VL    IN      ', name = "hunted" },
    { set = 'EX NH                     ', name = "a true leader" },
    { set = 'EX NH                AS   ', name = "indecision" },
    { set = 'EX NH             IN      ', name = "the friar" },
    { set = 'EX NH             IN AS   ', name = "black magic" },
    { set = 'EX NH          DH         ', name = "emperor's decadence" },
    { set = 'EX NH          DH IN AS   ', name = "futile spectacle" },
    { set = 'EX NH       VL       AS   ', name = "the scam leader" },
    { set = 'EX NH       VL    IN AS   ', name = "loading screen" },
    { set = 'EX NH    GV               ', name = "beyond death" },
    { set = 'EX NH    GV          AS   ', name = "beyond the afterdeath" },
    { set = 'EX NH    GV       IN      ', name = "still water" },
    { set = 'EX NH    GV       IN AS   ', name = "paragon" },
    { set = 'EX NH    GV    DH    AS   ', name = "the killscreen" },
    { set = 'EX NH    GV VL            ', name = "cutting edge" },
    { set = 'EX NH    GV VL    IN      ', name = "foresight" },
    { set = 'EX NH MS                  ', name = "online gambling" },
    { set = 'EX NH MS       DH         ', name = "impasse" },
    { set = 'EX NH MS    VL DH         ', name = "no holds barred" },
    { set = 'EX NH MS GV               ', name = "atlas' lament" },
    { set = 'EX NH MS GV VL            ', name = "oppression" },
}
