return {
    { name = [[a modern classic]],           set = 'NH GV',         basic = true },
    { name = [[deadlock]],                   set = 'MS NH DH',      basic = true },
    { name = [[the escape artist]],          set = 'MS DH AS',      basic = true },
    { name = [[the grandmaster]],            set = 'IN GV',         basic = true },
    { name = [[emperor's decadence]],        set = 'NH DH EX',      basic = true },
    { name = [[divine mastery]],             set = 'MS VL DH EX',   basic = true },
    { name = [[the starving artist]],        set = 'NH AS',         basic = true },
    { name = [[the con artist]],             set = 'VL AS EX',      basic = true },
    { name = [[trained profesionals]],       set = 'EX 2P',         basic = true },

    -- Contents below are ideas from tetr.io's community:
    -- https://docs.google.com/spreadsheets/d/1syh3q2oiduCZb1cJ5QI95Y2XhhedAfhv4YnEH9z2tbc
    { name = [[the abstract artist]],        set = 'IN AS' },
    { name = [[the deal with the devil]],    set = 'DH AS' },
    { name = [[the ghost]],                  set = 'DH IN' },
    { name = [[the libertine]],              set = 'DH IN AS' },
    { name = [[water from stone]],           set = 'VL AS' },
    { name = [[ruthlessness]],               set = 'VL IN' },
    { name = [[eccentric recluse]],          set = 'VL IN AS' },
    { name = [[lucifier]],                   set = 'VL DH' },
    { name = [[forbidden sorcery]],          set = 'VL DH AS' },
    { name = [[chasm]],                      set = 'VL DH IN' },
    { name = [[the juggler]],                set = 'GV AS' },
    { name = [[the grandmaster]],            set = 'GV IN' },
    { name = [[the spinmaster]],             set = 'GV IN AS' },
    { name = [[the speed demon]],            set = 'GV DH' },
    { name = [[the texting driver]],         set = 'GV DH AS' },
    { name = [[the drunk driver]],           set = 'GV DH IN' },
    { name = [[comfort food]],               set = 'GV VL' },
    { name = [[the gladiator]],              set = 'GV VL AS' },
    { name = [[connection issues]],          set = 'GV VL IN' },
    { name = [[immense pressure]],           set = 'GV VL IN AS' },
    { name = [[temptation]],                 set = 'GV VL DH' },
    { name = [[nightmare]],                  set = 'GV VL DH IN' },
    { name = [[roulette wheel]],             set = 'MS AS' },
    { name = [[blind bet]],                  set = 'MS IN' },
    { name = [[messy double hole]],          set = 'MS DH' },
    { name = [[the escape artist]],          set = 'MS DH AS' },
    { name = [[the stealth ninja]],          set = 'MS DH IN' },
    { name = [[nascent]],                    set = 'MS DH IN AS' },
    { name = [[swiss cheese]],               set = 'MS VL' },
    { name = [[cream cheese]],               set = 'MS VL AS' },
    { name = [[starstruck]],                 set = 'MS VL IN' },
    { name = [[utter trash]],                set = 'MS VL DH' },
    { name = [[blue cheese]],                set = 'MS VL DH AS' },
    { name = [[the night watchman]],         set = 'MS VL DH IN' },
    { name = [[cheese race]],                set = 'MS GV' },
    { name = [[rough sketch]],               set = 'MS GV AS' },
    { name = [[double down]],                set = 'MS GV DH' },
    { name = [[survival]],                   set = 'MS GV VL' },
    { name = [[mortal chaos]],               set = 'MS GV VL IN AS' },
    { name = [[quadruple down]],             set = 'MS GV VL DH' },
    { name = [[killer clown]],               set = 'MS GV VL DH AS' },
    { name = [[slaughterhouse]],             set = 'MS GV VL DH IN' },
    { name = [[the starving artist]],        set = 'NH AS' },
    { name = [[helen keller]],               set = 'NH IN' },
    { name = [[the blind artist]],           set = 'NH IN AS' },
    { name = [[purgatory]],                  set = 'NH DH' },
    { name = [[shapeshifter]],               set = 'NH DH AS' },
    { name = [[blindside]],                  set = 'NH DH IN' },
    { name = [[resistance]],                 set = 'NH VL' },
    { name = [[justice]],                    set = 'NH VL IN' },
    { name = [[judgment]],                   set = 'NH VL DH' },
    { name = [[the street artist]],          set = 'NH VL DH AS' },
    { name = [[a modern classic]],           set = 'NH GV' },
    { name = [[a modern twist]],             set = 'NH GV AS' },
    { name = [[evanescence]],                set = 'NH GV IN' },
    { name = [[divine failure]],             set = 'NH GV IN AS' },
    { name = [[damnation]],                  set = 'NH GV DH' },
    { name = [[backbar]],                    set = 'NH GV DH AS' },
    { name = [[cheat code]],                 set = 'NH GV DH IN AS' },
    { name = [[trational]],                  set = 'NH GV VL' },
    { name = [[the black hole]],             set = 'NH GV VL IN' },
    { name = [[nephalem]],                   set = 'NH GV VL DH' },
    { name = [[demonic possesion]],          set = 'NH GV VL DH AS' },
    { name = [[all in]],                     set = 'NH MS' },
    { name = [[deadlock]],                   set = 'NH MS DH' },
    { name = [[locksmith]],                  set = 'NH MS DH AS' },
    { name = [[unfinished business]],        set = 'NH MS DH IN' },
    { name = [[disappearance]],              set = 'NH MS DH IN AS' },
    { name = [[drowned]],                    set = 'NH MS VL IN' },
    { name = [[deadbolt]],                   set = 'NH MS VL DH' },
    { name = [[blind faith]],                set = 'NH MS VL DH IN' },
    { name = [[atlas' burden]],              set = 'NH MS GV' },
    { name = [[futile struggle]],            set = 'NH MS GV DH' },
    { name = [[misdrop haven]],              set = 'NH MS GV DH IN' },
    { name = [[quadruple threat]],           set = 'NH MS GV VL' },
    { name = [[quintuple threat]],           set = 'NH MS GV VL DH' },
    { name = [[dancing queen]],              set = 'EX AS' },
    { name = [[emperor's dilemma]],          set = 'EX IN' },
    { name = [[expertise]],                  set = 'EX IN AS' },
    { name = [[the devil's temptation]],     set = 'EX DH' },
    { name = [[loki]],                       set = 'EX DH AS' },
    { name = [[reverse quadruple threat]],   set = 'EX DH IN AS' },
    { name = [[icarus]],                     set = 'EX VL' },
    { name = [[the con artist]],             set = 'EX VL AS' },
    { name = [[bounty hunter]],              set = 'EX VL IN' },
    { name = [[insanity]],                   set = 'EX VL IN AS' },
    { name = [[the mad lord]],               set = 'EX VL DH' },
    { name = [[corruption]],                 set = 'EX VL DH IN' },
    { name = [[reverse quintuple threat]],   set = 'EX VL DH IN AS' },
    { name = [[inviticus]],                  set = 'EX GV' },
    { name = [[master of the t]],            set = 'EX GV AS' },
    { name = [[the super gm (grandmaster)]], set = 'EX GV IN' },
    { name = [[mastermind]],                 set = 'EX GV IN AS' },
    { name = [[the daredevil]],              set = 'EX GV DH' },
    { name = [[relaxation]],                 set = 'EX GV VL' },
    { name = [[enirsia ]],                   set = 'EX GV VL AS' },
    { name = [[lateness]],                   set = 'EX GV VL IN' },
    { name = [[speed the collapse]],         set = 'EX GV VL IN AS' },
    { name = [[rational reasoning]],         set = 'EX MS' },
    { name = [[the rich gambler]],           set = 'EX MS AS' },
    { name = [[the mathematician]],          set = 'EX MS IN AS' },
    { name = [[the wolf of wall street]],    set = 'EX MS VL' },
    { name = [[the hacker]],                 set = 'EX MS VL AS' },
    { name = [[reload]],                     set = 'EX MS VL IN AS' },
    { name = [[divine mastery]],             set = 'EX MS VL DH' },
    { name = [[false security]],             set = 'EX MS VL DH AS' },
    { name = [[mining operation]],           set = 'EX MS GV' },
    { name = [[mining for netherite]],       set = 'EX MS GV DH' },
    { name = [[juggernaut]],                 set = 'EX MS GV VL' },
    { name = [[hunted]],                     set = 'EX MS GV VL IN' },
    { name = [[a true leader]],              set = 'EX NH' },
    { name = [[indecision]],                 set = 'EX NH AS' },
    { name = [[the friar]],                  set = 'EX NH IN' },
    { name = [[black magic]],                set = 'EX NH IN AS' },
    { name = [[emperor's decadence]],        set = 'EX NH DH' },
    { name = [[futile spectacle]],           set = 'EX NH DH IN AS' },
    { name = [[the scam leader]],            set = 'EX NH VL AS' },
    { name = [[loading screen]],             set = 'EX NH VL IN AS' },
    { name = [[beyond death]],               set = 'EX NH GV' },
    { name = [[beyond the afterdeath]],      set = 'EX NH GV AS' },
    { name = [[still water]],                set = 'EX NH GV IN' },
    { name = [[paragon]],                    set = 'EX NH GV IN AS' },
    { name = [[the killscreen]],             set = 'EX NH GV DH AS' },
    { name = [[cutting edge]],               set = 'EX NH GV VL' },
    { name = [[foresight]],                  set = 'EX NH GV VL IN' },
    { name = [[online gambling]],            set = 'EX NH MS' },
    { name = [[impasse]],                    set = 'EX NH MS DH' },
    { name = [[no holds barred]],            set = 'EX NH MS VL DH' },
    { name = [[atlas' lament]],              set = 'EX NH MS GV' },
    { name = [[oppression]],                 set = 'EX NH MS GV VL' },
}
