GigaSpeedReq = { [0] = 7, 8, 8, 9, 9, 10, 1e99, 1e99, 1e99, 1e99, 1e99 }

GravityTimer = {
    { 9.0, 8.0, 7.5, 7.0, 6.5, 6.0, 5.5, 5.0, 4.5, 4.0 },
    { 3.2, 3.0, 2.8, 2.6, 2.5, 2.4, 2.3, 2.2, 2.1, 2.0 },
}

ModData = {
    deck = {
        { id = 'EX', initOrder = 1, lockfull = false },
        { id = 'NH', initOrder = 2, lockfull = true },
        { id = 'MS', initOrder = 3, lockfull = true },
        { id = 'GV', initOrder = 4, lockfull = true },
        { id = 'VL', initOrder = 5, lockfull = true },
        { id = 'DH', initOrder = 6, lockfull = true },
        { id = 'IN', initOrder = 7, lockfull = true },
        { id = 'AS', initOrder = 8, lockfull = true },
        { id = 'DP', initOrder = 9, lockfull = false },
    },
    name = {
        EX = 'expert',
        NH = 'nohold',
        MS = 'messy',
        GV = 'gravity',
        VL = 'volatile',
        DH = 'doublehole',
        IN = 'invisible',
        AS = 'allspin',
        DP = 'duo',
    },
    fullName = {
        EX = "< EXPERT MODE >",
        NH = "< NO HOLD >",
        MS = "< MESSIER GARBAGE  >",
        GV = "< GRAVITY >",
        VL = "< VOLATILE GARBAGE >",
        DH = "< DOUBLE HOLE GARBAGE >",
        IN = "< INVISIBLE >",
        AS = "< ALL-SPIN >",
        DP = "< DUO >",
        lock = "< LOCKED >",
        lockDP = "< LOCKED? >",
    },
    desc = {
        EX = "A LESS LENIENT CHALLENGE, FOR THOSE WHO DARE",
        NH = "CANCELING IS DISABLED",
        MS = "TAROTS WILL BE SHUFFLED BY FLOOR",
        GV = "AUTO COMMITTING, TIMED BY FLOOR",
        VL = "LARGER GAPS BETWEEN TAROTS, MUST CLICK TWICE",
        DH = "COMBOS WILL SPAWN HARDER",
        IN = "TAROTS FACE DOWN AND FLASH ONCE EVERY TWO SECONDS",
        AS = "ENABLE KEYBOARD, BUT DOUBLE CLICKING IS PENALIZED",
        DP = "FLOOD THE TOWER WITH SOMEONE WHO DOESN'T EXIST",
        lock = "REACH HIGHER FLOOR TO UNLOCK",
        lockDP = "MASTER THIS MOD TO UNLOCK",
    },
    revName = {
        EX = "> THE TYRANT <",
        NH = "> ASCETICISM <",
        MS = "> LOADED DICE <",
        GV = "> FREEFALL <",
        VL = "> LAST STAND <",
        DH = "> DAMNATION <",
        IN = "> THE EXILE <",
        AS = "> THE WARLOCK <",
        DP = "> BLEEDING HEARTS <",
    },
    revDesc = {
        EX = "FEAR, OPPRESSION, AND LIMITLESS AMBITION.",
        NH = "A DETACHMENT FROM EVEN THAT WHICH IS MODERATE.",
        MS = "IN A RIGGED GAME, YOUR MIND IS THE ONLY FAIR ADVANTAGE.",
        GV = "THE GROUND YOU STOOD ON NEVER EXISTED IN THE FIRST PLACE.",
        VL = "STRENGTH ISN'T NECESSARY FOR THOSE WITH NOTHING TO LOSE.",
        DH = "NO MORE SECOND CHANCES.",
        IN = "NEVER UNDERESTIMATE BLIND FAITH.",
        AS = "INTO REALMS BEYOND HEAVEN AND EARTH.",
        DP = "EVEN AS WE BLEED, WE KEEP HOLDING ON...",
    },
    weight = {
        EX = 13, --  8 + 5
        NH = 12, --  8 + 4
        MS = 14, -- 10 + 4
        GV = 12, -- 10 + 2
        VL = 17, -- 15 + 2
        DH = 12, --  8 + 4
        IN = 7,  --  6 + 1
        AS = 13, -- 10 + 3
        DP = 4,  --  3 + 1
    },
    color = {
        EX = { COLOR.HEX "89590B" },
        NH = { COLOR.HEX "FF00D4" },
        MS = { COLOR.HEX "FFB400" },
        GV = { COLOR.HEX "FFFF00" },
        VL = { COLOR.HEX "FF1500" },
        DH = { COLOR.HEX "47ACFF" },
        IN = { COLOR.HEX "BD24FF" },
        AS = { COLOR.HEX "00FED4" },
        DP = { COLOR.HEX "FF8C9D" },
    },
    textColor = {
        EX = { COLOR.HEX "C29F68" },
        NH = { COLOR.HEX "FF8BEC" },
        MS = { COLOR.HEX "FFD572" },
        GV = { COLOR.HEX "F7FF8A" },
        VL = { COLOR.HEX "FF978D" },
        DH = { COLOR.HEX "A6D5FF" },
        IN = { COLOR.HEX "E8B3FF" },
        AS = { COLOR.HEX "93FFE0" },
        DP = { COLOR.HEX "FFC0C9" },
    },
    prio_name = { IN = 0, MS = 1, VL = 2, NH = 3, DH = 4, AS = 5, GV = 6, EX = 7, DP = 8, rIN = 0, rMS = 1, rVL = 2, rNH = 3, rDH = 4, rAS = 5, rGV = 6, rEX = 7, rDP = 8 },
    prio_icon = { EX = 0, DP = 1, DH = 2, VL = 3, GV = 4, NH = 5, MS = 6, IN = 7, AS = 8, rEX = 0, rDP = 1, rDH = 2, rVL = 3, rGV = 4, rNH = 5, rMS = 6, rIN = 7, rAS = 8 },
    prio_card = { EX = 0, NH = 1, MS = 2, GV = 3, VL = 4, DH = 5, IN = 6, AS = 7, DP = 8, rEX = 0, rNH = 1, rMS = 2, rGV = 3, rVL = 4, rDH = 5, rIN = 6, rAS = 7, rDP = 8 },
    adj = {
        IN = "INVISIBLE",
        MS = "MESSY",
        VL = "VOLATILE",
        NH = "HOLDLESS",
        DH = "DOUBLE HOLE",
        AS = "ALL-SPIN",
        GV = "GRAVITY",
        EX = "EXPERT",
        DP = "DUO",
        rIN = "BELIEVED",
        rMS = "DECEPTIVE",
        rVL = "DESPERATE",
        rNH = "ASCENDANT",
        rDH = "DAMNED",
        rAS = "OMNI-SPIN",
        rGV = "COLLAPSED",
        rEX = "TYRANNICAL",
        rDP = "PIERCING",
    },
    noun = {
        IN = "INVISIBLITY",
        MS = "MESSINESS",
        VL = "VOLATILITY",
        NH = "NO HOLD",
        DH = "DOUBLE HOLE",
        AS = "ALL-SPIN",
        GV = "GRAVITY",
        EX = "EXPERT",
        DP = "DUO",
        rIN = "BELIEF",
        rMS = "DECEPTION",
        rVL = "DESPERATION",
        rNH = "ASCENSION",
        rDH = "DAMNATION",
        rAS = "OMNI-SPIN",
        rGV = "COLLAPSE",
        rEX = "TYRANNY",
        rDP = "HEARTACHE",
    },
}

ComboData = {
    -------- EX NH MS GV VL DH IN AS DP --------
    { set = '   NH    GV               ', name = "a modern classic",          basic = true },
    { set = '   NH MS       DH         ', name = "deadlock",                  basic = true },
    { set = '      MS       DH    AS   ', name = "the escape artist",         basic = true },
    { set = '         GV       IN      ', name = "the grandmaster",           basic = true },
    { set = 'EX NH          DH         ', name = "emperor's decadence",       basic = true },
    { set = 'EX    MS    VL DH         ', name = "divine mastery",            basic = true },
    { set = '   NH                AS   ', name = "the starving artist",       basic = true },
    { set = 'EX          VL       AS   ', name = "the con artist",            basic = true },
    { set = 'EX                      DP', name = "trained professionals",     basic = true },
    { set = 'EX    MS                  ', name = "block rationing",           basic = true },

    -- TODO: rev combos for achievements

    { set = '      MS          IN      ', name = "scrambled rainbow" },
    { set = 'EX NH                AS   ', name = "positioning master" },

    -- Contents below are ideas from tetr.io's community:
    -- https://docs.google.com/spreadsheets/d/1syh3q2oiduCZb1cJ5QI95Y2XhhedAfhv4YnEH9z2tbc
    { set = "AS",                         name = "the magician" },
    { set = "IN",                         name = "the hermit" },
    { set = "DH",                         name = "the abstract artist" },
    { set = "VL",                         name = "the devil" },
    { set = "GV",                         name = "the deal with the devil" },
    { set = "MS",                         name = "the ghost" },
    { set = "NH",                         name = "the libertine" },
    { set = "EX",                         name = "strength" },
    { set = "IN AS",                      name = "water from stone" },
    { set = "DH AS",                      name = "memorization" },
    { set = "DH IN",                      name = "eccentric recluse" },
    { set = "VL AS",                      name = "lucifer" },
    { set = "VL IN",                      name = "forbidden sorcery" },
    { set = "VL DH",                      name = "the flickering spirit" },
    { set = "GV AS",                      name = "the prodigy" },
    { set = "GV IN",                      name = "the tower" },
    { set = "GV DH",                      name = "the juggler" },
    { set = "GV VL",                      name = "the grandmaster" },
    { set = "GV VL",                      name = "the spinmaster" },
    { set = "MS AS",                      name = "the speed demon" },
    { set = "MS IN",                      name = "the texting driver" },
    { set = "MS DH",                      name = "the drunk driver" },
    { set = "MS VL",                      name = "horror thriller" },
    { set = "MS GV",                      name = "comfort food" },
    { set = "NH AS",                      name = "leap of faith" },
    { set = "NH IN",                      name = "the gladiator" },
    { set = "NH DH",                      name = "paranoia" },
    { set = "NH VL",                      name = "immense pressure" },
    { set = "NH GV",                      name = "temptation" },
    { set = "NH MS",                      name = "sword box" },
    { set = "NH MS",                      name = "nightmare" },
    { set = "EX AS",                      name = "lost genius" },
    { set = "EX IN",                      name = "wheel of fortune" },
    { set = "EX DH",                      name = "roulette wheel" },
    { set = "EX VL",                      name = "blind bet" },
    { set = "EX GV",                      name = "abstraction" },
    { set = "EX MS",                      name = "dig in" },
    { set = "EX NH",                      name = "the escape artist" },
    { set = "DH IN AS",                   name = "the stealth ninja" },
    { set = "VL IN AS",                   name = "nascent" },
    { set = "VL DH AS",                   name = "swiss cheese" },
    { set = "VL DH IN",                   name = "cream cheese" },
    { set = "GV IN AS",                   name = "starstruck" },
    { set = "GV DH AS",                   name = "creative explosion" },
    { set = "GV DH IN",                   name = "utter trash" },
    { set = "GV VL AS",                   name = "divine apprentice" },
    { set = "GV VL IN",                   name = "blue cheese" },
    { set = "GV VL DH",                   name = "the night watchman" },
    { set = "MS IN AS",                   name = "beethoven" },
    { set = "MS DH AS",                   name = "cheese race" },
    { set = "MS DH IN",                   name = "rough sketch" },
    { set = "MS VL AS",                   name = "burrata" },
    { set = "MS VL IN",                   name = "parmigiano reggiano" },
    { set = "MS VL DH",                   name = "double down" },
    { set = "MS VL DH",                   name = "the spacial artist" },
    { set = "MS GV AS",                   name = "intoxication" },
    { set = "MS GV IN",                   name = "doubled symbolism" },
    { set = "MS GV DH",                   name = "survival" },
    { set = "MS GV VL",                   name = "gambled faith" },
    { set = "NH IN AS",                   name = "eleventh hour" },
    { set = "NH DH AS",                   name = "mortal chaos" },
    { set = "NH DH IN",                   name = "quadruple down" },
    { set = "NH VL AS",                   name = "killer clown" },
    { set = "NH VL IN",                   name = "slaughterhouse" },
    { set = "NH VL DH",                   name = "hidden circus" },
    { set = "NH GV AS",                   name = "temperance" },
    { set = "NH GV IN",                   name = "the starving artist" },
    { set = "NH GV IN",                   name = "helen keller" },
    { set = "NH GV DH",                   name = "the blind artist" },
    { set = "NH GV DH",                   name = "purgatory" },
    { set = "NH GV VL",                   name = "shapeshifter" },
    { set = "NH MS AS",                   name = "blindside" },
    { set = "NH MS IN",                   name = "impressionism" },
    { set = "NH MS DH",                   name = "resistance" },
    { set = "NH MS VL",                   name = "bob ross" },
    { set = "NH MS GV",                   name = "justice" },
    { set = "EX IN AS",                   name = "vigilante" },
    { set = "EX DH AS",                   name = "judgment" },
    { set = "EX DH IN",                   name = "the restrained artist" },
    { set = "EX VL AS",                   name = "spilled milk" },
    { set = "EX VL IN",                   name = "magic" },
    { set = "EX VL DH",                   name = "a modern classic" },
    { set = "EX GV AS",                   name = "a modern twist" },
    { set = "EX GV IN",                   name = "evanescence" },
    { set = "EX GV DH",                   name = "the absolute grandmaster" },
    { set = "EX GV VL",                   name = "divine failure" },
    { set = "EX MS AS",                   name = "no holds barred" },
    { set = "EX MS IN",                   name = "ill fate" },
    { set = "EX MS DH",                   name = "dance dance revolution" },
    { set = "EX MS VL",                   name = "backbar" },
    { set = "EX MS GV",                   name = "live fast die young" },
    { set = "EX NH AS",                   name = "cheat code" },
    { set = "EX NH IN",                   name = "traditional" },
    { set = "EX NH DH",                   name = "recreation" },
    { set = "EX NH VL",                   name = "the black hole" },
    { set = "EX NH GV",                   name = "ergosphere" },
    { set = "EX NH MS",                   name = "nephalem" },
    { set = "VL DH IN AS",                name = "demonic possession" },
    { set = "GV DH IN AS",                name = "entropy" },
    { set = "GV VL IN AS",                name = "hell" },
    { set = "GV VL DH AS",                name = "the gambler" },
    { set = "GV VL DH IN",                name = "all in" },
    { set = "MS DH IN AS",                name = "unpredictable outcome" },
    { set = "MS VL IN AS",                name = "the false prophet" },
    { set = "MS VL DH AS",                name = "writer's block" },
    { set = "MS VL DH IN",                name = "deadlock" },
    { set = "MS GV IN AS",                name = "locksmith" },
    { set = "MS GV DH AS",                name = "unfinished business" },
    { set = "MS GV DH IN",                name = "disappearance" },
    { set = "MS GV VL AS",                name = "the glass cannon" },
    { set = "MS GV VL IN",                name = "bluff" },
    { set = "MS GV VL DH",                name = "deadbolt" },
    { set = "NH DH IN AS",                name = "boltsmith" },
    { set = "NH VL IN AS",                name = "blind faith" },
    { set = "NH VL DH AS",                name = "deadhook" },
    { set = "NH VL DH IN",                name = "atlas' burden" },
    { set = "NH GV IN AS",                name = "futility" },
    { set = "NH GV DH AS",                name = "a classic escape" },
    { set = "NH GV DH AS",                name = "misdrop haven" },
    { set = "NH GV DH IN",                name = "quadruple threat" },
    { set = "NH GV VL AS",                name = "quintuple threat" },
    { set = "NH GV VL IN",                name = "sextuple threat" },
    { set = "NH GV VL DH",                name = "septuple threat" },
    { set = "NH MS IN AS",                name = "the emperor" },
    { set = "NH MS DH AS",                name = "dancing queen" },
    { set = "NH MS DH IN",                name = "emperor's dilemma" },
    { set = "NH MS VL AS",                name = "expertise" },
    { set = "NH MS VL DH",                name = "the devil's temptation" },
    { set = "NH MS GV DH",                name = "loki" },
    { set = "NH MS GV VL",                name = "the architect" },
    { set = "EX DH IN AS",                name = "reverse quadruple threat" },
    { set = "EX VL IN AS",                name = "icarus" },
    { set = "EX VL DH AS",                name = "the con artist" },
    { set = "EX VL DH IN",                name = "bounty hunter" },
    { set = "EX GV IN AS",                name = "insanity" },
    { set = "EX GV DH AS",                name = "the mad lord" },
    { set = "EX GV VL AS",                name = "devilish falsifier" },
    { set = "EX GV VL IN",                name = "corruption" },
    { set = "EX GV VL DH",                name = "reverse quintuple threat" },
    { set = "EX MS IN AS",                name = "invictus" },
    { set = "EX MS DH AS",                name = "master of the t" },
    { set = "EX MS VL AS",                name = "the super gm (grandmaster)" },
    { set = "EX MS VL IN",                name = "mastermind" },
    { set = "EX MS VL DH",                name = "the daredevil" },
    { set = "EX MS GV AS",                name = "spin overlord" },
    { set = "EX MS GV DH",                name = "relaxation" },
    { set = "EX MS GV VL",                name = "enirsia " },
    { set = "EX NH IN AS",                name = "lateness" },
    { set = "EX NH DH AS",                name = "speed the collapse" },
    { set = "EX NH VL AS",                name = "the autocrat" },
    { set = "EX NH VL IN",                name = "unexpectancy" },
    { set = "EX NH VL DH",                name = "all out" },
    { set = "EX NH GV AS",                name = "block rationing" },
    { set = "EX NH GV IN",                name = "the rich gambler" },
    { set = "EX NH GV IN",                name = "irrational" },
    { set = "EX NH GV VL",                name = "the mathematician" },
    { set = "EX NH MS AS",                name = "no warning" },
    { set = "EX NH MS DH",                name = "imprisonment" },
    { set = "EX NH MS VL",                name = "the wolf of wall street" },
    { set = "EX NH MS GV",                name = "the hacker" },
    { set = "GV VL DH IN AS",             name = "interstellar" },
    { set = "MS VL DH IN AS",             name = "reload" },
    { set = "MS GV DH IN AS",             name = "divine mastery" },
    { set = "MS GV VL IN AS",             name = "false security" },
    { set = "MS GV VL DH AS",             name = "garbage soda" },
    { set = "MS GV VL DH IN",             name = "mining operation" },
    { set = "NH VL DH IN AS",             name = "irregular sketch" },
    { set = "NH GV DH IN AS",             name = "mining for netherite" },
    { set = "NH GV VL IN AS",             name = "the temporal artist" },
    { set = "NH GV VL DH AS",             name = "juggernaut" },
    { set = "NH GV VL DH IN",             name = "deadline" },
    { set = "NH MS DH IN AS",             name = "hunted" },
    { set = "NH MS VL DH AS",             name = "researcher" },
    { set = "NH MS VL DH IN",             name = "hell's gate" },
    { set = "NH MS GV DH AS",             name = "chaos" },
    { set = "NH MS GV DH IN",             name = "disorder" },
    { set = "NH MS GV VL DH",             name = "a fair leader" },
    { set = "EX VL DH IN AS",             name = "indecision" },
    { set = "EX GV VL IN AS",             name = "the friar" },
    { set = "EX GV VL DH IN",             name = "black magic" },
    { set = "EX MS VL IN AS",             name = "emperor's decadence" },
    { set = "EX MS VL DH AS",             name = "amorphous" },
    { set = "EX MS GV DH AS",             name = "futile spectacle" },
    { set = "EX MS GV VL AS",             name = "archangel" },
    { set = "EX MS GV VL IN",             name = "the scam leader" },
    { set = "EX MS GV VL DH",             name = "unreasonable" },
    { set = "EX NH DH IN AS",             name = "loading screen" },
    { set = "EX NH VL IN AS",             name = "azathoth" },
    { set = "EX NH VL DH AS",             name = "loss of control" },
    { set = "EX NH VL DH IN",             name = "spoiled milk" },
    { set = "EX NH GV IN AS",             name = "beyond death" },
    { set = "EX NH GV DH AS",             name = "beyond the afterdeath" },
    { set = "EX NH GV VL IN",             name = "still water" },
    { set = "EX NH GV VL DH",             name = "jack of all trades" },
    { set = "EX NH MS VL DH",             name = "paragon" },
    { set = "EX NH MS GV VL",             name = "the kill screen" },
    { set = "MS GV VL DH IN AS",          name = "immortal" },
    { set = "NH GV VL DH IN AS",          name = "cutting edge" },
    { set = "NH MS VL DH IN AS",          name = "foresight" },
    { set = "NH MS GV VL DH IN",          name = "distilled water" },
    { set = "EX GV VL DH IN AS",          name = "the veteran" },
    { set = "EX MS VL DH IN AS",          name = "spinny thingy" },
    { set = "EX MS GV VL IN AS",          name = "methodical " },
    { set = "EX MS GV VL DH AS",          name = "online gambling" },
    { set = "EX MS GV VL DH IN",          name = "fair chance" },
    { set = "EX NH GV DH IN AS",          name = "impasse" },
    { set = "EX NH GV VL IN AS",          name = "encryption" },
    { set = "EX NH GV VL DH AS",          name = "the fugitive" },
    { set = "EX NH GV VL DH IN",          name = "mastery" },
    { set = "EX NH MS DH IN AS",          name = "no holds barred" },
    { set = "EX NH MS VL IN AS",          name = "reinforced lock" },
    { set = "EX NH MS VL DH AS",          name = "the artist trinity" },
    { set = "EX NH MS VL DH AS",          name = "epitome" },
    { set = "EX NH MS VL DH IN",          name = "atlas' lament" },
    { set = "EX NH MS GV IN AS",          name = "the matrix" },
    { set = "EX NH MS GV DH IN",          name = "blandness" },
    { set = "EX NH MS GV VL AS",          name = "oppression" },
    { set = "EX NH MS GV VL IN",          name = "on screen keyboard" },
    { set = "EX NH MS GV VL DH",          name = "depression" },
}

RevComboData = {
    "Z", "S", "J", "L", "T", "O", "I",
    [["BLIGHT"]],
    [["DESOLATION"]],
    [["HAVOC"]],
    [["PANDEMONIUM"]],
    [["INFERNO"]],
    [["PURGATORY"]],
    [["PERDITION"]],
    [["CATACLYSM"]],
    [["ANNIHILATION"]],
    [["ARMAGEDDON"]],
    [["ABYSS"]],
    [["APOCALYPSE"]], -- not used
}

Floors = {
    [0] = { top = 0, name = "The Basement" },
    { top = 50,   event = {},                                                  name = "Hall of Beginnings" },
    { top = 150,  event = { 'dmgDelay', -2, 'dmgWrong', 1 },                   name = "The Hotel",           MSshuffle = true },
    { top = 300,  event = { 'dmgDelay', -2, 'dmgCycle', -.5 },                 name = "The Casino" },
    { top = 450,  event = { 'dmgDelay', -1, 'dmgCycle', -.5 },                 name = "The Arena" },
    { top = 650,  event = { 'dmgDelay', -1, 'dmgCycle', -.5, 'dmgWrong', 1 },  name = "The Museum",          MSshuffle = true },
    { top = 850,  event = { 'dmgDelay', -1, 'dmgTime', 1, 'maxQuestSize', 1 }, name = "Abandoned Offices" },
    { top = 1100, event = { 'dmgDelay', -1, 'dmgCycle', -.5 },                 name = "The Laboratory",      MSshuffle = true },
    { top = 1350, event = { 'dmgDelay', -1, 'dmgCycle', -.5 },                 name = "The Core" },
    { top = 1650, event = { 'dmgDelay', -.5, 'dmgWrong', 1 },                  name = "Corruption",          MSshuffle = true },
    { top = 1e99, event = { 'dmgDelay', -.5, 'dmgCycle', -.5, 'dmgTime', 1 },  name = "Platform of the Gods" },
    -- Initial: Delay=15. Cycle=5, Wrong=1
    -- Total: Delay-10, Cycle-3, Wrong+4
}

Fatigue = {
    normal = {
        { time = 300,  event = { 'dmgTimeMul', -.1 },                                         text = "FATIGUE SETS IN_",          desc = "TimerSpeed++" },
        { time = 330,  event = { 'dmgCycle', -.5, 'dmgWrong', 1 },                            text = "YOUR BODY GROWS WEAK_",     desc = "DmgCycle--   Damage++" },
        { time = 360,  event = { 'dmgTimeMul', -.1, 'dmgHeal', -1 },                          text = "ALL SENSES BLUR TOGETHER_", desc = "TimerSpeed++   Heal--" },
        { time = 390,  event = { 'dmgTimeMul', -.1, 'dmgWrong', 1 },                          text = "YOUR CONSCIOUSNESS FADES_", desc = "TimerSpeed++   Damage++" },
        { time = 420,  event = { 'dmgTimeMul', -.2, 'dmgCycle', -.5 },                        text = "THIS IS THE END.",          desc = "TimerSpeed++   DmgCycle--" },
        { time = 480,  event = { 'maxQuestSize', 1, 'extraQuestVar', 1, 'atkBufferCap', 18 }, text = "FAREWELL.",                 desc = "QuestDifficulty++++++" },
        { time = 1e99, text = "" }, -- Total: dmgTimeMul-50%, Cycle-1, Wrong+2
    },
    rEX = {
        { time = 240,  event = { 'dmgTimeMul', -.2 },                 text = "YOUR POWER SLIPS_",               desc = "TimerSpeed++" },
        { time = 270,  event = { 'dmgWrong', 2 },                     text = "WHISPERS OF DISCONTENT SPREAD_",  desc = "Damage++" },
        { time = 300,  event = { 'dmgCycle', -1 },                    text = "PROTESTERS LINE THE STREETS_",    desc = "DmgCycle--" },
        { time = 330,  event = { 'dmgTimeMul', -.2, 'dmgWrong', 2, }, text = "YOUR CLOSEST ALLIES DEFECT_",     desc = "TimerSpeed++   Damage++" },
        { time = 360,  event = { 'dmgTimeMul', -.2, 'dmgHeal', -1 },  text = "PARANOIA CLOUDS YOUR JUDGEMENT_", desc = "TimerSpeed++   Heal--" },
        { time = 390,  event = { 'dmgCycle', -.5, 'dmgWrong', 1 },    text = "THE REVOLUTION HAS BEGUN_",       desc = "DmgCycle--   Damage++" },
        { time = 420,  event = { 'dmgTimeMul', -.3 },                 text = "THE END OF AN ERA.",              desc = "TimerSpeed++++" },
        { time = 1e99, text = "" }, -- Total: dmgTimeMul-90%, Cycle-1, Wrong+5
    },
    rDP = {
        { time = 20,   event = { 'dmgHeal', -1 }, --[[ 2 ]]    text = "YOUR PASSION FADES_",                        desc = "Heal-" },
        { time = 40,   event = { 'dmgHeal', -.5 }, --[[ 1.5 ]] text = "THEIR REPLIES BECOME LESS ENGAGED_",         desc = "Heal--" },
        { time = 60,   event = { 'dmgHeal', -.5 }, --[[ 1 ]]   text = "YOU FEEL NEGLECTED_",                        desc = "Heal---" },
        { time = 80,   event = { 'dmgHeal', 1 }, --[[ 2 ]]     text = "THEY SUCCESSFULLY APOLOGIZE_?",              desc = "Heal+",         color = 'lO' },
        { time = 100,  event = { 'dmgHeal', 1 }, --[[ 3 ]]     text = "THINGS ARE BACK TO HOW THEY USED TO BE_!",   desc = "Heal+++",       color = 'lO' },
        { time = 120,  event = { 'dmgHeal', -1 }, --[[ 2 ]]    text = "MINOR ISSUES BECOME LARGE CONFLICTS_",       desc = "Heal--" },
        { time = 140,  event = { 'dmgHeal', -1 }, --[[ 1 ]]    text = "YOU BLAME THEM FOR YOUR OWN PROBLEMS_",      desc = "Heal---" },
        { time = 160,  event = { 'reviveCount', 3 },           text = "THEY WOULD RATHER SPEND TIME ALONE_",        desc = "Revive++" },
        { time = 180,  event = { 'dmgHeal', 1.5 }, --[[ 2.5 ]] text = "YOU PROMISE TO CHANGE_",                     desc = "Heal++",        color = 'lO' },
        { time = 200,  event = { 'dmgTimeMul', -.2 },          text = "PROMISES ARE BROKEN_",                       desc = "TimerSpeed++" },
        { time = 220,  event = { 'dmgHeal', -.5 }, --[[ 2 ]]   text = "CONVERSATIONS DEVOLVE TO SHOUTING MATCHES_", desc = "Heal---" },
        { time = 240,  event = { 'dmgHeal', -.5 }, --[[ 1.5 ]] text = "ALL TRUST HAS WITHERED AWAY_",               desc = "Heal--" },
        { time = 260,  event = { 'dmgHeal', -.5 }, --[[ 1 ]]   text = "THEY SET AN ULTIMATUM_",                     desc = "Heal--" },
        { time = 280,  event = { 'dmgHeal', -.5 }, --[[ .5 ]]  text = "YOU CAN'T BE BOTHERED ANYMORE_",             desc = "Heal--" },
        { time = 300,  event = { 'dmgWrong', 2 },              text = "ONE LAST PAINFUL ARGUMENT_",                 desc = "Dmg+" },
        { time = 320,  event = { 'reviveCount', 260 },         text = "GOODBYE.",                                   desc = "NO REVIVE" },
        { time = 360,  event = { 'dmgHeal', 1 }, --[[ 1.5 ]]   text = "\"I MISS YOU\"",                             desc = "Heal+++",       color = 'lO' },
        { time = 380,  event = { 'dmgHeal', 1 }, --[[ 2.5 ]]   text = "MAYBE IT CAN STILL WORK_?",                  desc = "Heal+",         color = 'lO' },
        { time = 400,  event = { 'dmgTimeMul', -.5 },          text = "GOODBYE.",                                   desc = "TimerSpeed++++" },
        { time = 1e99, text = "" }, -- Total: dmgTimeMul-70%
    },
}
-- My formatter doesn't work if there's "…" inside
for _, f in next, Fatigue do for _, v in next, f do v.text = v.text:gsub("_", "…") end end

local function rndMod(t)
    local d = ModData.deck[math.random(9)].id
    t.prompt = t.prompt:repD(d)
    t.text = t.text:repD(ModData.adj[d])
    t.short = t.short:repD(d)
end
local function f5() return GAME.floor <= 5 end
local function F6() return GAME.floor >= 6 end
local function F9() return GAME.floor >= 9 end

---@class Prompt
---@field rank number[]
---@field prompt string
---@field target number
---@field short string
---@field text string
---@field cond? fun():boolean
---@field init? fun(t:Prompt)

---@type Prompt[]
RevivePrompts = {
    { rank = { 1, 2 }, prompt = 'activate',             target = 30,  short = "Activate 30",             text = "Activate 30 cards" },
    { rank = { 3, 4 }, prompt = 'activate',             target = 80,  short = "Activate 80",             text = "Activate 80 cards" },
    { rank = { 2, 2 }, prompt = 'cancel',               target = 40,  short = "Cancel 40",               text = "Cancel 40 cards" },
    { rank = { 3, 4 }, prompt = 'cancel',               target = 100, short = "Cancel 100",              text = "Cancel 100 cards" },
    { rank = { 1, 2 }, prompt = 'flip',                 target = 50,  short = "Flip 50",                 text = "Flip 50 cards" },
    { rank = { 3, 4 }, prompt = 'flip',                 target = 120, short = "Flip 120",                text = "Flip 120 cards" },
    { rank = { 5, 6 }, prompt = 'flip',                 target = 300, short = "Flip 300",                text = "Flip 300 cards" },
    { rank = { 1, 2 }, prompt = 'flip_single',          target = 10,  short = "Flip single 10",          text = "Flip a single card\n10 times in a row" },
    { rank = { 2, 4 }, prompt = 'flip_single',          target = 20,  short = "Flip single 20",          text = "Flip a single card\n20 times in a row" },
    { rank = { 1, 2 }, prompt = 'commit',               target = 6,   short = "Commit 6x",               text = "Commit 6 times" },
    { rank = { 2, 3 }, prompt = 'commit',               target = 15,  short = "Commit 15x",              text = "Commit 15 times" },
    { rank = { 3, 5 }, prompt = 'commit',               target = 30,  short = "Commit 30x",              text = "Commit 30 times" },
    { rank = { 1, 2 }, prompt = 'commit_$1',            target = 2,   short = "Commit $1 2x",            text = "Commit 2 times\nwith $1",                     init = rndMod },
    { rank = { 3, 4 }, prompt = 'commit_$1',            target = 4,   short = "Commit $1 4x",            text = "Commit 4 times\nwith $1",                     init = rndMod },
    { rank = { 2, 4 }, prompt = 'commit_$1_row',        target = 2,   short = "2 Chain with $1",         text = "Commit 2 times\nwith $1 in a row",            init = rndMod },
    { rank = { 3, 6 }, prompt = 'commit_$1_row',        target = 3,   short = "3 Chain with $1",         text = "Commit 3 times\nwith $1 in a row",            init = rndMod },
    { rank = { 1, 3 }, prompt = 'commit_no_$1_row',     target = 2,   short = "2 chain without $1",      text = "Commit 2 times\nwithout $1 in a row",         init = rndMod },
    { rank = { 3, 5 }, prompt = 'commit_no_$1_row',     target = 3,   short = "3 chain without $1",      text = "Commit 3 times\nwithout $1 in a row",         init = rndMod },
    { rank = { 1, 2 }, prompt = 'commit_0',             target = 2,   short = "Commit NOTHING 2x",       text = "Commit NOTHING\n2 times" },
    { rank = { 2, 4 }, prompt = 'commit_0',             target = 5,   short = "Commit NOTHING 5x",       text = "Commit NOTHING\n5 times" },
    { rank = { 4, 6 }, prompt = 'commit_0',             target = 8,   short = "Commit NOTHING 8x",       text = "Commit NOTHING\n8 times" },
    { rank = { 1, 3 }, prompt = 'commit_0_row',         target = 3,   short = "3x Spam commit",          text = "Commit NOTHING\n3 times in a row" },
    { rank = { 3, 5 }, prompt = 'commit_no_conn',       target = 1,   short = "Commit no consec",        text = "Commit without consecutive cards",            cond = F6 },
    { rank = { 1, 4 }, prompt = 'commit_conn_2',        target = 1,   short = "Commit 2 consec",         text = "Commit with 2 consecutive cards",             cond = f5 },
    { rank = { 2, 4 }, prompt = 'commit_conn_3',        target = 1,   short = "Commit 3 consec",         text = "Commit with 3 consecutive cards",             cond = f5 },
    { rank = { 3, 5 }, prompt = 'commit_conn_4',        target = 1,   short = "Commit 4 consec",         text = "Commit with 4 consecutive cards" },
    { rank = { 3, 5 }, prompt = 'commit_swamp_l',       target = 1,   short = "SWAMP WATER LITE",        text = "Commit SWAMP WATER LITE" },
    { rank = { 4, 6 }, prompt = 'commit_swamp',         target = 1,   short = "SWAMP WATER",             text = "Commit SWAMP WATER" },
    { rank = { 3, 6 }, prompt = 'commit_reversed',      target = 1,   short = "Commit inversed",         text = "Commit all cards\nwhich are not requested" },
    { rank = { 1, 4 }, prompt = 'commit_1card',         target = 3,   short = "Commit 1 cards 3x",       text = "Commit 3 times with\n1 card on first commit" },
    { rank = { 2, 5 }, prompt = 'commit_2card',         target = 4,   short = "Commit 2 cards 4x",       text = "Commit 4 times with\n2 cards on first commit" },
    { rank = { 3, 6 }, prompt = 'commit_3card',         target = 5,   short = "Commit 3 cards 5x",       text = "Commit 5 times with\n3 cards on first commit" },
    { rank = { 4, 6 }, prompt = 'commit_4card',         target = 4,   short = "Commit 4 cards 4x",       text = "Commit 4 times with\n4 cards on first commit" },
    { rank = { 5, 6 }, prompt = 'commit_5card',         target = 3,   short = "Commit 5 cards 3x",       text = "Commit 3 times with\n5 cards on first commit" },
    { rank = { 1, 4 }, prompt = 'pass',                 target = 10,  short = "Pass 10",                 text = "Pass 10 times" },
    { rank = { 5, 6 }, prompt = 'pass',                 target = 20,  short = "Pass 20",                 text = "Pass 20 times" },
    { rank = { 2, 5 }, prompt = 'pass_$1',              target = 2,   short = "Pass 2 with $1",          text = "Pass 2 times\nwith $1",                       init = rndMod },
    { rank = { 3, 5 }, prompt = 'pass_$1',              target = 3,   short = "Pass 3 with $1",          text = "Pass 3 times\nwith $1",                       init = rndMod },
    { rank = { 4, 6 }, prompt = 'pass_$1',              target = 4,   short = "Pass 4 with $1",          text = "Pass 4 times\nwith $1",                       init = rndMod },
    { rank = { 2, 4 }, prompt = 'pass_perfect',         target = 6,   short = "6x perf",                 text = "Pass 6 times perfectly" },
    { rank = { 5, 6 }, prompt = 'pass_perfect',         target = 12,  short = "12x perf",                text = "Pass 12 times perfectly" },
    { rank = { 2, 4 }, prompt = 'pass_imperfect',       target = 6,   short = "6x im-perf",              text = "Pass 6 times imperfectly" },
    { rank = { 5, 6 }, prompt = 'pass_imperfect',       target = 12,  short = "12x im-perf",             text = "Pass 12 times imperfectly" },
    { rank = { 4, 5 }, prompt = 'pass_imperfect_row',   target = 3,   short = "3x chain im-perf",        text = "Pass 3 times\nimperfectly in a row" },
    { rank = { 5, 6 }, prompt = 'pass_imperfect_row',   target = 8,   short = "8x chain im-perf",        text = "Pass 8 times\nimperfectly in a row" },
    { rank = { 2, 4 }, prompt = 'pass_perfect_row',     target = 4,   short = "B2B x 4",                 text = "Reach B2B x 4" },
    { rank = { 3, 5 }, prompt = 'pass_perfect_row',     target = 6,   short = "B2B x 6",                 text = "Reach B2B x 6" },
    { rank = { 4, 5 }, prompt = 'pass_perfect_row',     target = 8,   short = "B2B x 8",                 text = "Reach B2B x 8" },
    { rank = { 4, 6 }, prompt = 'pass_perfect_row',     target = 10,  short = "B2B x 10",                text = "Reach B2B x 10" },
    { rank = { 2, 3 }, prompt = 'pass_second',          target = 4,   short = "2nd quest 4x",            text = "Pass the second\nquest 4 times" },
    { rank = { 3, 4 }, prompt = 'pass_second',          target = 8,   short = "2nd quest 8x",            text = "Pass the second\nquest 8 times" },
    { rank = { 4, 5 }, prompt = 'pass_second',          target = 12,  short = "2nd quest 12x",           text = "Pass the second\nquest 12 times" },
    { rank = { 2, 4 }, prompt = 'b2b_break_4',          target = 1,   short = "Break B2B 4x",            text = "Break B2B x 4" },
    { rank = { 3, 4 }, prompt = 'b2b_break_6',          target = 1,   short = "Break B2B 6x",            text = "Break B2B x 6" },
    { rank = { 4, 5 }, prompt = 'b2b_break_8',          target = 1,   short = "Break B2B 8x",            text = "Break B2B x 8" },
    { rank = { 4, 6 }, prompt = 'b2b_break_10',         target = 1,   short = "Break B2B 10x",           text = "Break B2B x 10" },
    { rank = { 4, 6 }, prompt = 'b2b_break_windup',     target = 1,   short = "Break B2B at a windup",   text = "Break B2B at a windup",                       cond = F9 },
    { rank = { 5, 6 }, prompt = 'b2b_break_windup3',    target = 1,   short = "Break B2B at a windup3+", text = "Break B2B at\na lv.3+ windup",                cond = F9 },
    { rank = { 1, 3 }, prompt = 'heal',                 target = 8,   short = "Heal 8 HP",               text = "Heal 8 HP" },
    { rank = { 2, 4 }, prompt = 'heal',                 target = 20,  short = "Heal 20 HP",              text = "Heal 20 HP" },
    { rank = { 1, 2 }, prompt = 'send',                 target = 6,   short = "Send 6",                  text = "Send 6 attacks" },
    { rank = { 3, 4 }, prompt = 'send',                 target = 20,  short = "Send 20",                 text = "Send 20 attacks" },
    { rank = { 5, 6 }, prompt = 'send',                 target = 40,  short = "Send 40",                 text = "Send 40 attacks" },
    { rank = { 3, 4 }, prompt = 'pass_windup',          target = 1,   short = "Windup",                  text = "Pass a windup",                               cond = F9 },
    { rank = { 3, 5 }, prompt = 'pass_windup3',         target = 1,   short = "Windup3+",                text = "Pass a lv.3+ windup",                         cond = F9 },
    { rank = { 5, 5 }, prompt = 'pass_windup_inb2b',    target = 1,   short = "Windup with B2B",         text = "Pass a windup\nduring one B2B charge",        cond = F9 },
    { rank = { 4, 5 }, prompt = 'pass_windup',          target = 4,   short = "Windup x 4",              text = "Pass 4 windups",                              cond = F9 },
    { rank = { 4, 4 }, prompt = 'pass_windup_perfect',  target = 1,   short = "Windup perf",             text = "Pass a windup\nperfectly",                    cond = F9 },
    { rank = { 6, 6 }, prompt = 'pass_windup_inb2b',    target = 3,   short = "Windup x 3 with B2B",     text = "Pass 4 windups\nduring a B2B charge",         cond = F9 },
    { rank = { 5, 5 }, prompt = 'pass_windup_perfect',  target = 4,   short = "Windup perf x 4",         text = "Pass 4 windups\nperfectly",                   cond = F9 },
    { rank = { 5, 5 }, prompt = 'pass_windup3_perfect', target = 1,   short = "Windup3+ perf",           text = "Pass a lv.3+\nwindup perfectly",              cond = F9 },
    { rank = { 6, 6 }, prompt = 'pass_windup3_perfect', target = 4,   short = "Windup3+ perf x 4",       text = "Pass 4 lv.3+\nwindups perfectly",             cond = F9 },
    { rank = { 2, 2 }, prompt = 'dmg_time',             target = 4,   short = "Take Dmg 4x",             text = "Take damage 4 times" },
    { rank = { 3, 3 }, prompt = 'dmg_time',             target = 8,   short = "Take Dmg 8x",             text = "Take damage 8 times" },
    { rank = { 2, 4 }, prompt = 'dmg_amount',           target = 10,  short = "Lose 10 HP",              text = "Take 10 damage total" },
    { rank = { 4, 6 }, prompt = 'dmg_amount',           target = 20,  short = "Lose 20 HP",              text = "Take 20 damage total" },
    { rank = { 3, 4 }, prompt = 'timedmg_time',         target = 2,   short = "Take Time Dmg 2x",        text = "Take time damage 2 times",                    cond = F6 },
    { rank = { 5, 6 }, prompt = 'timedmg_time',         target = 4,   short = "Take Time Dmg 4x",        text = "Take time damage 4 times",                    cond = F6 },
    { rank = { 4, 6 }, prompt = 'keep_health_safe',     target = 8,   short = "Safe HP 8s",              text = "Keep HP safe for\n8 seconds",                 cond = F6 },
    { rank = { 4, 5 }, prompt = 'keep_health_danger',   target = 3,   short = "Danger HP 3s",            text = "Keep HP in danger\nfor 3 seconds",            cond = F6 },
    { rank = { 2, 5 }, prompt = 'keep_no_mouse',        target = 4,   short = "No mouse 4s",             text = "Don't touch mouse\nfor 4 seconds",            cond = f5 },
    { rank = { 2, 4 }, prompt = 'keep_no_commit',       target = 6,   short = "No commit 6s",            text = "Don't commit\nfor 6 seconds",                 cond = f5 },
    { rank = { 3, 6 }, prompt = 'keep_no_cancel',       target = 8,   short = "No cancel 8s",            text = "Don't cancel\nfor 8 seconds" },
    { rank = { 2, 5 }, prompt = 'keep_no_keyboard',     target = 10,  short = "No keyboard 10s",         text = "Don't touch keyboard\nfor 10 seconds",        cond = F6 },
    { rank = { 3, 5 }, prompt = 'keep_no_perfect',      target = 12,  short = "No perfect 12s",          text = "Don't perfect\nfor 12 seconds" },
    { rank = { 4, 6 }, prompt = 'keep_no_imperfect',    target = 14,  short = "No imperfect 14s",        text = "Don't imperfect\nfor 14 seconds",             cond = F6 },
    { rank = { 3, 5 }, prompt = 'keep_no_reset',        target = 16,  short = "No reset 16s",            text = "Don't reset\nfor 16 seconds" },
}

Achievements = {
    -- Single Mod
    EX = { "The Emperor", "HFD with EX", [[A display of power for those willing to bear its burden.]] },
    NH = { "Temperance", "HFD with NH", [[Use each piece as they come and embrace the natural flow of stacking.]] },
    MS = { "Wheel of Fortune", "HFD with MS", [[The only constant in life is change.]] },
    GV = { "The Tower", "HFD with GV", [[What will you do when it all comes crumbling down?]] },
    VL = { "Strength", "HFD with VL", [[Match great obstacles with greater determination.]] },
    DH = { "The Devil", "HFD with DH", [[Redifine your limits or succumb to his chains.]] },
    IN = { "The Hermit", "HFD with IN", [[When the outside world fails you, trust the voice within to light a path.]] },
    AS = { "The Magician", "HFD with AS", [[Inspiration is nothing short of magic.]] },
    DP = { "The Lovers", "HFD with DP", [[Love, and resign yourself to the fate of another.]] },
    rEX = { "The Tyrant", "HFD with rEX", [[Fear, oppression, and limitless ambition.]] },
    rNH = { "Asceticism", "HFD with rNH", [[A detachment from even that which is moderate.]] },
    rMS = { "Loaded Dice", "HFD with rMS", [[In a rigged game, your mind is the only fair advantage.]] },
    rGV = { "Freefall", "HFD with rGV", [[In retrospect, the ground you stood on never existed in the first place.]] },
    rVL = { "Last Stand", "HFD with rVL", [[Strength isn't necessary for those with nothing to lose.]] },
    rDH = { "Damnation", "HFD with rDH", [[No more second chances.]] },
    rIN = { "The Exile", "HFD with rIN", [[Never underestimate blind faith.]] },
    rAS = { "The Warlock", "HFD with rAS", [[Into realms beyond heaven and earth.]] },
    rDP = { "Bleeding Hearts", "HFD with rDP", [[Even as we bleed, we keep holding on…]] },

    -- Mod Combo
    NH_GV = { "A Modern Classic", "HFD with NH GV", [[Times were different back then...]] },
    NH_MS_DH = { "Deadlock", "HFD with NH MS DH", [["Escape has become a distant dream, yet still we struggle..."]] },
    MS_DH_AS = { "The Escape Artist", "HFD with MS DH AS", [["An impossible situation! A daring illusionist! Will he make it out alive?"]] },
    GV_IN = { "The Grandmaster", "HFD with GV IN", [[When the world descends into chaos, the grandmaster remains at peace.]] },
    EX_NH_DH = { "Emperor's Decadence", "HFD with EX NH DH", [[The Devil's lesson in humility.]] },
    EX_MS_VL_DH = { "Divine Mastery", "HFD with EX MS VL DH", [[The universe is yours.]] },
    NH_AS = { "The Starving Artist", "HFD with NH AS", [[Creativity cultivated trough limitation.]] },
    EX_VL_AS = { "The Con Artist", "HFD with EX VL AS", [[Would the perfect lie not be an art worthy of admiration?]] },
    EX_DP = { "Trained Professionals", "HFD with EX DP", [[Partners in expertise.]] },
    EX_MS = { "Block Rationing", "HFD with EX MS", [[Adversity favors the resourceful.]] },

    -- Swamp Water Series
    SWLite = { "Swamp Water Lite", "HFD with 7 mods", [[Comes in... 36 different flavors!]] },
    SW = { "Swamp Water", "HFD with 8 mods", [[The worst of all worlds.]] },

    -- General
    Zenith_Explorer = { "Zenith Explorer", "HFD", [[Uncover the mysteries of the Zenith Tower.]] },
    Zenith_Speedrun = { "Zenith Speedrun", "Reach F10 AFAP while retaining GIGASPEED (nomod)", [[F10 Hyper%]] },
    Supercharged = { "Supercharged", "Highest Back-to-Back chain discovered (nomod)", [["With this divine power, we'll be unstoppable!" -Mathis, Core Engineer]] },
    The_Responsible_One = { "The Responsible One", "Highest amount of revivals performed in a single duo run", [["Could you please stop dying?"]] },
    Guardian_Angel = { "Guardian Angel", "Highest altitude to perform a successful revive at", [[An angel's intervention.]] },
    Talentless = { "Talentless", "HFD with AS but mouse-only", [[Reaching deep down but coming back empty every time.]] },

    -- Activity
    lovers_promise = { "Lover's Promise", "Highest altitude reached with DP on Valentine's / White / Black Day / Double Seventh Festival", [[The impossible promise of an eternity just like this moment.]] },



    -- Rev Swamp Water Series
    blight = { "Blight", "HFD with 8+ mod points (F4/6/8/9/10)", [[The world starts withering...]] },
    desolation = { "Desolation", "HFD with 9+ mod points (F4/6/8/9/10)", [[Vitality has faded from the world's palette...]] },
    havoc = { "Havoc", "HFD with 10+ mod points (F3/5/8/9/10)", [[The world is in chaos...]] },
    pandemonium = { "Pandemonium", "HFD with 11+ mod points (F2/4/7/8/9)", [[Several realms began to collide...]] },
    inferno = { "Inferno", "HFD with 12+ mod points (F2/4/6/7/8)", [[Everything is burning and melting...]] },
    purgatory = { "Purgatory", "HFD with 13+ mod points (F1/3/5/6/7)", [[Nobody knows their destination...]] },
    perdition = { "Perdition", "HFD with 14+ mod points (F1/3/4/5/6)", [[There's no way back...]] },
    cataclysm = { "Cataclysm", "HFD with 15+ mod points (F1/2/3/4/5)", [[The real disaster is yet to come...]] },
    annihilation = { "Annihilation", "HFD with 16+ mod points (F1/2/3/4)", [[The whole universe is trembling...]] },
    armageddon = { "Armageddon", "HFD with 17+ mod points (F1/2/3)", [[Big crunch is real...]] },
    abyss = { "Abyss", "HFD with 18 mod points (F1/2)", [[.]] },

    -- Swamp Water Series
    SWPro = { "Swamp Water Pro", "HFD with 9 mods", [[How did you find someone as insane as you to do it together?]] },
    SWLiteP = { "Swamp Water Lite+", "HFD with 7+ mods, including 1 rev", [[Comes in...... 252 different flavors?]] },
    SWP = { "Swamp Water+", "HFD with 8+ mods, including 1 rev", [[Less choices but still a lot to try.]] },
    SWProP = { "Swamp Water Pro+", "HFD with 9 mods, including 1 rev", [[The cup is about to overflow!]] },

    -- Other Mod Combos
    -- TODO

    -- Issued
    -- TODO
}

for _, achv in next, Achievements do
    achv[2] = achv[2]:gsub("HFD", "Highest floor discovered"):gsub("AFAP", "as fast as possible")
end
