GigaSpeedReq = { [0] = 7, 8, 8, 9, 9, 10, 1e99, 1e99, 1e99, 1e99, 1e99 }

GravityTimer = {
    { 9.0, 8.0, 7.5, 7.0, 6.5, 6.0, 5.5, 5.0, 4.5, 4.0 },
    { 3.2, 3.0, 2.8, 2.6, 2.5, 2.4, 2.3, 2.2, 2.1, 2.0 },
}

ModData = {
    deck = {
        { id = 'EX', initOrder = 1, lockfull = false },
        { id = 'NH', initOrder = 2, lockfull = true },
        { id = 'MS', initOrder = 3, lockfull = true },
        { id = 'GV', initOrder = 4, lockfull = true },
        { id = 'VL', initOrder = 5, lockfull = true },
        { id = 'DH', initOrder = 6, lockfull = true },
        { id = 'IN', initOrder = 7, lockfull = true },
        { id = 'AS', initOrder = 8, lockfull = true },
        { id = 'DP', initOrder = 9, lockfull = false },
    },
    name = {
        EX = 'expert',
        NH = 'nohold',
        MS = 'messy',
        GV = 'gravity',
        VL = 'volatile',
        DH = 'doublehole',
        IN = 'invisible',
        AS = 'allspin',
        DP = 'duo',
    },
    fullName = {
        EX = "< EXPERT MODE >",
        NH = "< NO HOLD >",
        MS = "< MESSIER GARBAGE  >",
        GV = "< GRAVITY >",
        VL = "< VOLATILE GARBAGE >",
        DH = "< DOUBLE HOLE GARBAGE >",
        IN = "< INVISIBLE >",
        AS = "< ALL-SPIN >",
        DP = "< DUO >",
        lock = "< LOCKED >",
        lockDP = "< LOCKED? >",
    },
    desc = {
        EX = "A LESS LENIENT CHALLENGE, FOR THOSE WHO DARE",
        NH = "CANCELING IS DISABLED",
        MS = "TAROTS WILL BE SHUFFLED BY FLOOR",
        GV = "AUTO COMMITTING, TIMED BY FLOOR",
        VL = "LARGER GAPS BETWEEN TAROTS, MUST CLICK TWICE",
        DH = "COMBOS WILL SPAWN HARDER",
        IN = "TAROTS FACE DOWN AND FLASH ONCE EVERY TWO SECONDS",
        AS = "ENABLE KEYBOARD, BUT DOUBLE CLICKING IS PENALIZED",
        DP = "FLOOD THE TOWER WITH SOMEONE WHO DOESN'T EXIST",
        lock = "REACH HIGHER FLOOR TO UNLOCK",
        lockDP = "MASTER THIS MOD TO UNLOCK",
    },
    revName = {
        EX = "> THE TYRANT <",
        NH = "> ASCETICISM <",
        MS = "> LOADED DICE <",
        GV = "> FREEFALL <",
        VL = "> LAST STAND <",
        DH = "> DAMNATION <",
        IN = "> THE EXILE <",
        AS = "> THE WARLOCK <",
        DP = "> BLEEDING HEARTS <",
    },
    revDesc = {
        EX = "FEAR, OPPRESSION, AND LIMITLESS AMBITION.",
        NH = "A DETACHMENT FROM EVEN THAT WHICH IS MODERATE.",
        MS = "IN A RIGGED GAME, YOUR MIND IS THE ONLY FAIR ADVANTAGE.",
        GV = "THE GROUND YOU STOOD ON NEVER EXISTED IN THE FIRST PLACE.",
        VL = "STRENGTH ISN'T NECESSARY FOR THOSE WITH NOTHING TO LOSE.",
        DH = "NO MORE SECOND CHANCES.",
        IN = "NEVER UNDERESTIMATE BLIND FAITH.",
        AS = "INTO REALMS BEYOND HEAVEN AND EARTH.",
        DP = "EVEN AS WE BLEED, WE KEEP HOLDING ON...",
    },
    weight = {
        EX = 13, --  8 + 5
        NH = 12, --  8 + 4
        MS = 14, -- 10 + 4
        GV = 12, -- 10 + 2
        VL = 17, -- 15 + 2
        DH = 12, --  8 + 4
        IN = 7,  --  6 + 1
        AS = 13, -- 10 + 3
        DP = 4,  --  3 + 1
    },
    color = {
        EX = { COLOR.HEX "89590B" },
        NH = { COLOR.HEX "FF00D4" },
        MS = { COLOR.HEX "FFB400" },
        GV = { COLOR.HEX "FFFF00" },
        VL = { COLOR.HEX "FF1500" },
        DH = { COLOR.HEX "47ACFF" },
        IN = { COLOR.HEX "BD24FF" },
        AS = { COLOR.HEX "00FED4" },
        DP = { COLOR.HEX "FF8C9D" },
    },
    textColor = {
        EX = { COLOR.HEX "C29F68" },
        NH = { COLOR.HEX "FF8BEC" },
        MS = { COLOR.HEX "FFD572" },
        GV = { COLOR.HEX "F7FF8A" },
        VL = { COLOR.HEX "FF978D" },
        DH = { COLOR.HEX "A6D5FF" },
        IN = { COLOR.HEX "E8B3FF" },
        AS = { COLOR.HEX "93FFE0" },
        DP = { COLOR.HEX "FFC0C9" },
    },
    prio_name = { IN = 0, MS = 1, VL = 2, NH = 3, DH = 4, AS = 5, GV = 6, EX = 7, DP = 8, rIN = 0, rMS = 1, rVL = 2, rNH = 3, rDH = 4, rAS = 5, rGV = 6, rEX = 7, rDP = 8 },
    prio_icon = { EX = 0, DP = 1, DH = 2, VL = 3, GV = 4, NH = 5, MS = 6, IN = 7, AS = 8, rEX = 0, rDP = 1, rDH = 2, rVL = 3, rGV = 4, rNH = 5, rMS = 6, rIN = 7, rAS = 8 },
    prio_card = { EX = 0, NH = 1, MS = 2, GV = 3, VL = 4, DH = 5, IN = 6, AS = 7, DP = 8, rEX = 0, rNH = 1, rMS = 2, rGV = 3, rVL = 4, rDH = 5, rIN = 6, rAS = 7, rDP = 8 },
    adj = {
        IN = "INVISIBLE",
        MS = "MESSY",
        VL = "VOLATILE",
        NH = "HOLDLESS",
        DH = "DOUBLE HOLE",
        AS = "ALL-SPIN",
        GV = "GRAVITY",
        EX = "EXPERT",
        DP = "DUO",
        rIN = "BELIEVED",
        rMS = "DECEPTIVE",
        rVL = "DESPERATE",
        rNH = "ASCENDANT",
        rDH = "DAMNED",
        rAS = "OMNI-SPIN",
        rGV = "COLLAPSED",
        rEX = "TYRANNICAL",
        rDP = "PIERCING",
    },
    noun = {
        IN = "INVISIBLITY",
        MS = "MESSINESS",
        VL = "VOLATILITY",
        NH = "NO HOLD",
        DH = "DOUBLE HOLE",
        AS = "ALL-SPIN",
        GV = "GRAVITY",
        EX = "EXPERT",
        DP = "DUO",
        rIN = "BELIEF",
        rMS = "DECEPTION",
        rVL = "DESPERATION",
        rNH = "ASCENSION",
        rDH = "DAMNATION",
        rAS = "OMNI-SPIN",
        rGV = "COLLAPSE",
        rEX = "TYRANNY",
        rDP = "HEARTACHE",
    },
}

ComboData = {
    -------- EX NH MS GV VL DH IN AS DP --------
    { set = 'NH GV',             name = "a modern classic",                   basic = true },
    { set = 'NH MS DH',          name = "deadlock",                           basic = true },
    { set = 'MS DH AS',          name = "the escape artist",                  basic = true },
    { set = 'GV IN',             name = "the grandmaster",                    basic = true },
    { set = 'EX NH DH',          name = "emperor's decadence",                basic = true },
    { set = 'EX MS VL DH',       name = "divine mastery",                     basic = true },
    { set = 'NH AS',             name = "the starving artist",                basic = true },
    { set = 'EX VL AS',          name = "the con artist",                     basic = true },
    { set = 'EX DP',             name = "trained professionals",              basic = true },
    { set = 'EX MS',             name = "block rationing",                    basic = true },

    -- Achievement combos
    { set = "rNH rGV rVL",       name = "sweatshop",                          menu = true },
    { set = "NH rAS",            name = "pristine",                           menu = true },
    { set = "rEX rDP",           name = "tyrannical dyarchy",                 menu = true },
    { set = "VL rIN rDP",        name = "painful relapse",                    menu = true },
    { set = "rDH rIN",           name = "brain capacity",                     menu = true },
    { set = "EX rGV DH",         name = "demonic speed",                      menu = true },
    { set = "rNH MS GV DP",      name = "grand-master! rounds",               menu = true },
    { set = "rNH rIN",           name = "instant memory",                     menu = true },
    { set = "EX NH rMS GV",      name = "bnuuy",                              menu = true },
    { set = "GV rDH rAS",        name = "storage overload",                   menu = true },
    { set = "NH DH rIN rAS",     name = "steganography",                      menu = true },
    { set = "rGV rAS",           name = "whizzing wizard",                    menu = true },
    { set = "DH DP",             name = "museum heist",                       menu = true },

    -- rDH database
    { set = 'MS IN',             name = "scrambled rainbow",                  ex = true },
    { set = 'EX NH AS',          name = "positioning master",                 ex = true },
    -- Contents below are ideas from tetr.io's community:
    -- https://docs.google.com/spreadsheets/d/1syh3q2oiduCZb1cJ5QI95Y2XhhedAfhv4YnEH9z2tbc
    { set = "EX",                name = "the emperor",                        ex = true },
    { set = "NH",                name = "temperance",                         ex = true },
    { set = "MS",                name = "wheel of fortune",                   ex = true },
    { set = "GV",                name = "the tower",                          ex = true },
    { set = "VL",                name = "strength",                           ex = true },
    { set = "DH",                name = "the devil",                          ex = true },
    { set = "IN",                name = "the hermit",                         ex = true },
    { set = "AS",                name = "the magician",                       ex = true },
    { set = "DP",                name = "the lovers",                         ex = true },
    { set = "MS DH",             name = "dig in",                             ex = true },
    { set = "NH MS",             name = "all in",                             ex = true },
    { set = "EX VL",             name = "icarus",                             ex = true },
    { set = "VL DH",             name = "lucifer",                            ex = true },
    { set = "EX GV",             name = "invictus",                           ex = true },
    { set = "DH IN",             name = "the ghost",                          ex = true },
    { set = "MS IN",             name = "blind bet",                          ex = true },
    { set = "NH DH",             name = "purgatory lite",                     ex = true }, -- name used
    { set = "NH VL",             name = "resistance",                         ex = true },
    { set = "GV AS",             name = "the juggler",                        ex = true },
    { set = "MS GV",             name = "cheese race",                        ex = true },
    { set = "NH MS",             name = "the gambler",                        ex = true },
    { set = "VL IN",             name = "memorization",                       ex = true },
    { set = "GV VL",             name = "comfort food",                       ex = true },
    { set = "MS VL",             name = "swiss cheese",                       ex = true },
    { set = "NH IN",             name = "helen keller",                       ex = true },
    { set = "GV VL",             name = "leap of faith",                      ex = true },
    { set = "EX AS",             name = "dancing queen",                      ex = true },
    { set = "EX NH",             name = "a fair leader",                      ex = true },
    { set = "MS AS",             name = "roulette wheel",                     ex = true },
    { set = "GV IN",             name = "the grandmaster",                    ex = true },
    { set = "GV DH",             name = "the speed demon",                    ex = true },
    { set = "EX MS",             name = "block rationing",                    ex = true },
    { set = "VL AS",             name = "water from stone",                   ex = true },
    { set = "NH GV",             name = "a modern classic",                   ex = true },
    { set = "EX IN",             name = "emperor's dilemma",                  ex = true },
    { set = "IN AS",             name = "the abstract artist",                ex = true },
    { set = "NH AS",             name = "the starving artist",                ex = true },
    { set = "EX DH",             name = "the devil's temptation",             ex = true },
    { set = "DH AS",             name = "the deal with the devil",            ex = true },
    { set = "EX DH AS",          name = "loki",                               ex = true },
    { set = "MS GV IN",          name = "burrata",                            ex = true },
    { set = "NH VL IN",          name = "justice",                            ex = true },
    { set = "GV VL IN",          name = "paranoia",                           ex = true },
    { set = "MS GV VL",          name = "survival",                           ex = true },
    { set = "NH VL AS",          name = "bob ross",                           ex = true },
    { set = "NH VL DH",          name = "judgment",                           ex = true },
    { set = "NH GV DH",          name = "ill fate",                           ex = true },
    { set = "NH MS DH",          name = "deadlock",                           ex = true },
    { set = "NH DH IN",          name = "blindside",                          ex = true },
    { set = "EX IN AS",          name = "expertise",                          ex = true },
    { set = "EX NH IN",          name = "the friar",                          ex = true },
    { set = "EX NH VL",          name = "archangel",                          ex = true },
    { set = "GV VL DH",          name = "temptation",                         ex = true },
    { set = "MS VL IN",          name = "starstruck",                         ex = true },
    { set = "EX GV VL",          name = "relaxation",                         ex = true },
    { set = "EX MS IN",          name = "irrational",                         ex = true },
    { set = "EX MS DH",          name = "no warning",                         ex = true },
    { set = "EX NH AS",          name = "indecision",                         ex = true },
    { set = "MS IN AS",          name = "abstraction",                        ex = true },
    { set = "MS VL DH",          name = "utter trash",                        ex = true },
    { set = "MS GV DH",          name = "double down",                        ex = true },
    { set = "NH GV IN",          name = "evanescence",                        ex = true },
    { set = "NH GV VL",          name = "traditional",                        ex = true },
    { set = "MS VL AS",          name = "cream cheese",                       ex = true },
    { set = "MS GV AS",          name = "rough sketch",                       ex = true },
    { set = "NH DH AS",          name = "shapeshifter",                       ex = true },
    { set = "EX VL DH",          name = "the mad lord",                       ex = true },
    { set = "EX NH GV",          name = "beyond death",                       ex = true },
    { set = "DH IN AS",          name = "the libertine",                      ex = true },
    { set = "GV VL AS",          name = "the gladiator",                      ex = true },
    { set = "NH MS GV",          name = "atlas' burden",                      ex = true },
    { set = "EX DH IN",          name = "the architect",                      ex = true },
    { set = "EX VL IN",          name = "bounty hunter",                      ex = true },
    { set = "EX GV DH",          name = "the daredevil",                      ex = true },
    { set = "GV IN AS",          name = "the spinmaster",                     ex = true },
    { set = "MS VL DH",          name = "cheese factory",                     ex = true },
    { set = "NH GV AS",          name = "a modern twist",                     ex = true },
    { set = "EX VL AS",          name = "the con artist",                     ex = true },
    { set = "NH GV DH",          name = "no holds barred",                    ex = true },
    { set = "EX GV AS",          name = "master of the t",                    ex = true },
    { set = "EX NH MS",          name = "online gambling",                    ex = true },
    { set = "GV DH IN",          name = "the drunk driver",                   ex = true },
    { set = "NH IN AS",          name = "the blind artist",                   ex = true },
    { set = "NH MS VL",          name = "the glass cannon",                   ex = true },
    { set = "EX MS AS",          name = "the rich gambler",                   ex = true },
    { set = "EX MS GV",          name = "mining operation",                   ex = true },
    { set = "VL IN AS",          name = "eccentric recluse",                  ex = true },
    { set = "VL DH AS",          name = "forbidden sorcery",                  ex = true },
    { set = "MS DH AS",          name = "the escape artist",                  ex = true },
    { set = "MS DH IN",          name = "the stealth ninja",                  ex = true },
    { set = "MS VL DH",          name = "divine apprentice",                  ex = true },
    { set = "NH MS IN",          name = "the false prophet",                  ex = true },
    { set = "GV DH AS",          name = "the texting driver",                 ex = true },
    { set = "EX NH DH",          name = "emperor's decadence",                ex = true },
    { set = "VL DH IN",          name = "the flickering spirit",              ex = true },
    { set = "NH MS AS",          name = "unpredictable outcome",              ex = true },
    { set = "EX MS VL",          name = "the wolf of wall street",            ex = true },
    { set = "NH GV IN",          name = "the absolute grandmaster",           ex = true },
    { set = "EX GV IN",          name = "the super gm",                       ex = true },
    { set = "NH MS VL AS",       name = "bluff",                              ex = true },
    { set = "MS DH IN AS",       name = "nascent",                            ex = true },
    { set = "NH GV DH AS",       name = "backbar",                            ex = true },
    { set = "EX GV VL AS",       name = "enirsia",                            ex = true },
    { set = "EX NH MS DH",       name = "impasse",                            ex = true },
    { set = "NH GV VL DH",       name = "nephalem",                           ex = true },
    { set = "NH MS VL DH",       name = "deadbolt",                           ex = true },
    { set = "NH MS GV DH",       name = "futility",                           ex = true },
    { set = "EX VL IN AS",       name = "insanity",                           ex = true },
    { set = "EX GV VL IN",       name = "lateness",                           ex = true },
    { set = "EX NH VL DH",       name = "azathoth",                           ex = true },
    { set = "GV VL DH AS",       name = "sword box",                          ex = true },
    { set = "GV VL DH IN",       name = "nightmare",                          ex = true },
    { set = "NH VL IN AS",       name = "vigilante",                          ex = true },
    { set = "NH MS DH AS",       name = "locksmith",                          ex = true },
    { set = "EX NH DH AS",       name = "amorphous",                          ex = true },
    { set = "NH GV VL AS",       name = "recreation",                         ex = true },
    { set = "EX VL DH IN",       name = "corruption",                         ex = true },
    { set = "EX GV IN AS",       name = "mastermind",                         ex = true },
    { set = "EX MS VL AS",       name = "the hacker",                         ex = true },
    { set = "EX MS GV VL",       name = "juggernaut",                         ex = true },
    { set = "VL DH IN AS",       name = "the prodigy",                        ex = true },
    { set = "MS VL DH AS",       name = "blue cheese",                        ex = true },
    { set = "EX NH IN AS",       name = "black magic",                        ex = true },
    { set = "EX NH GV IN",       name = "still water",                        ex = true },
    { set = "EX NH MS AS",       name = "fair chance",                        ex = true },
    { set = "MS GV DH IN",       name = "intoxication",                       ex = true },
    { set = "NH VL DH IN",       name = "spilled milk",                       ex = true },
    { set = "EX GV VL DH",       name = "the autocrat",                       ex = true },
    { set = "EX MS DH AS",       name = "imprisonment",                       ex = true },
    { set = "EX MS VL IN",       name = "interstellar",                       ex = true },
    { set = "EX NH VL IN",       name = "unreasonable",                       ex = true },
    { set = "EX NH GV VL",       name = "cutting edge",                       ex = true },
    { set = "EX NH MS VL",       name = "the fugitive",                       ex = true },
    { set = "MS GV VL AS",       name = "gambled faith",                      ex = true },
    { set = "MS GV VL IN",       name = "eleventh hour",                      ex = true },
    { set = "NH DH IN AS",       name = "impressionism",                      ex = true },
    { set = "EX GV DH AS",       name = "spin overlord",                      ex = true },
    { set = "MS GV VL DH",       name = "quadruple down",                     ex = true },
    { set = "NH GV IN AS",       name = "divine failure",                     ex = true },
    { set = "NH GV VL IN",       name = "the black hole",                     ex = true },
    { set = "NH MS IN AS",       name = "writer's block",                     ex = true },
    { set = "EX MS VL DH",       name = "divine mastery",                     ex = true },
    { set = "GV DH IN AS",       name = "horror thriller",                    ex = true },
    { set = "EX NH VL AS",       name = "the scam leader",                    ex = true },
    { set = "GV VL IN AS",       name = "immense pressure",                   ex = true },
    { set = "NH MS GV VL",       name = "quadruple threat",                   ex = true },
    { set = "EX MS GV AS",       name = "irregular sketch",                   ex = true },
    { set = "EX MS IN AS",       name = "the mathematician",                  ex = true },
    { set = "MS VL IN AS",       name = "creative explosion",                 ex = true },
    { set = "MS VL DH IN",       name = "the night watchman",                 ex = true },
    { set = "MS GV DH AS",       name = "the spacial artist",                 ex = true },
    { set = "EX VL DH AS",       name = "devilish falsifier",                 ex = true },
    { set = "EX NH GV IN",       name = "jack of all trades",                 ex = true },
    { set = "MS GV IN AS",       name = "parmigiano reggiano",                ex = true },
    { set = "NH GV DH IN",       name = "live fast die young",                ex = true },
    { set = "NH MS DH IN",       name = "unfinished business",                ex = true },
    { set = "EX MS GV DH",       name = "mining for netherite",               ex = true },
    { set = "NH VL DH AS",       name = "the restrained artist",              ex = true },
    { set = "EX NH GV AS",       name = "beyond the afterdeath",              ex = true },
    { set = "NH GV DH AS",       name = "dance dance revolution",             ex = true },
    { set = "EX DH IN AS",       name = "reverse quadruple threat",           ex = true },
    { set = "NH VL DH IN AS",    name = "magic",                              ex = true },
    { set = "EX MS VL IN AS",    name = "reload",                             ex = true },
    { set = "EX MS GV VL IN",    name = "hunted",                             ex = true },
    { set = "NH GV VL DH IN",    name = "entropy",                            ex = true },
    { set = "EX NH GV IN AS",    name = "paragon",                            ex = true },
    { set = "EX MS GV VL AS",    name = "deadline",                           ex = true },
    { set = "MS VL DH IN AS",    name = "beethoven",                          ex = true },
    { set = "NH MS VL DH AS",    name = "boltsmith",                          ex = true },
    { set = "EX NH GV VL IN",    name = "foresight",                          ex = true },
    { set = "NH GV DH IN AS",    name = "cheat code",                         ex = true },
    { set = "NH GV VL IN AS",    name = "ergosphere",                         ex = true },
    { set = "EX NH MS GV VL",    name = "oppression",                         ex = true },
    { set = "GV VL DH IN AS",    name = "lost genius",                        ex = true },
    { set = "NH MS VL DH IN",    name = "blind faith",                        ex = true },
    { set = "EX MS GV VL DH",    name = "hell's gate",                        ex = true },
    { set = "EX NH GV VL DH",    name = "the veteran",                        ex = true },
    { set = "MS GV VL IN AS",    name = "mortal chaos",                       ex = true },
    { set = "MS GV VL DH AS",    name = "killer clown",                       ex = true },
    { set = "EX GV VL DH IN",    name = "unexpectancy",                       ex = true },
    { set = "EX NH VL DH IN",    name = "spoiled milk",                       ex = true },
    { set = "NH MS DH IN AS",    name = "disappearance",                      ex = true },
    { set = "NH MS GV DH IN",    name = "misdrop haven",                      ex = true },
    { set = "MS GV VL DH IN",    name = "slaughterhouse",                     ex = true },
    { set = "EX MS VL DH AS",    name = "false security",                     ex = true },
    { set = "EX NH VL IN AS",    name = "loading screen",                     ex = true },
    { set = "EX NH VL DH AS",    name = "loss of control",                    ex = true },
    { set = "EX NH GV DH AS",    name = "the kill screen",                    ex = true },
    { set = "EX NH MS VL DH",    name = "no holds barred",                    ex = true },
    { set = "NH MS GV DH AS",    name = "a classic escape",                   ex = true },
    { set = "NH MS GV VL DH",    name = "quintuple threat",                   ex = true },
    { set = "EX NH DH IN AS",    name = "futile spectacle",                   ex = true },
    { set = "MS GV DH IN AS",    name = "doubled symbolism",                  ex = true },
    { set = "NH GV VL DH AS",    name = "demonic possession",                 ex = true },
    { set = "EX GV VL IN AS",    name = "speed the collapse",                 ex = true },
    { set = "EX MS GV DH AS",    name = "the temporal artist",                ex = true },
    { set = "EX VL DH IN AS",    name = "reverse quintuple threat",           ex = true },
    { set = "NH GV VL DH IN AS", name = "hell",                               ex = true },
    { set = "EX MS GV VL DH AS", name = "chaos",                              ex = true },
    { set = "EX GV VL DH IN AS", name = "all out",                            ex = true },
    { set = "EX NH MS VL IN AS", name = "mastery",                            ex = true },
    { set = "EX NH MS VL DH IN", name = "epitome",                            ex = true },
    { set = "NH MS VL DH IN AS", name = "deadhook",                           ex = true },
    { set = "EX MS GV VL DH IN", name = "disorder",                           ex = true },
    { set = "EX NH GV DH IN AS", name = "immortal",                           ex = true },
    { set = "EX NH MS GV DH IN", name = "blandness",                          ex = true },
    { set = "EX MS GV VL IN AS", name = "researcher",                         ex = true },
    { set = "EX NH GV VL DH IN", name = "methodical",                         ex = true },
    { set = "EX NH MS DH IN AS", name = "encryption",                         ex = true },
    { set = "EX NH MS GV IN AS", name = "the matrix",                         ex = true },
    { set = "EX NH MS GV VL IN", name = "depression",                         ex = true },
    { set = "EX MS VL DH IN AS", name = "garbage soda",                       ex = true },
    { set = "MS GV VL DH IN AS", name = "hidden circus",                      ex = true },
    { set = "EX NH GV VL DH AS", name = "spinny thingy",                      ex = true },
    { set = "NH MS GV VL DH IN", name = "sextuple threat",                    ex = true },
    { set = "EX NH GV VL IN AS", name = "distilled water",                    ex = true },
    { set = "EX NH MS VL DH AS", name = "reinforced lock",                    ex = true },
    { set = "EX NH MS VL DH AS", name = "the artist trinity",                 ex = true },
    { set = "EX NH MS GV VL AS", name = "on screen keyboard",                 ex = true },
    { set = "EX NH MS GV VL DH", name = "diluted lite diet swamp water zero", ex = true },
}

for i = 1, #ComboData do
    local cmb = ComboData[i]
    cmb.name = '"' .. cmb.name:upper() .. '"'
    local cmbStr = table.concat(TABLE.sort(cmb.set:trim():split('%s+', true)), ' ')
    ComboData[cmbStr] = ComboData[cmbStr] or cmb
end

RevSwampName = {
    "Z", "S", "J", "L", "T", "O", "I",
    [["BLIGHT"]],
    [["DESOLATION"]],
    [["HAVOC"]],
    [["PANDEMONIUM"]],
    [["INFERNO"]],
    [["PURGATORY"]],
    [["PERDITION"]],
    [["CATACLYSM"]],
    [["ANNIHILATION"]],
    [["ARMAGEDDON"]],
    [["ABYSS"]],
    [["APOCALYPSE"]], -- not used
}

Floors = {
    [0] = { top = 0, name = "The Basement" },
    { top = 50,   event = {},                                                  name = "Hall of Beginnings" },
    { top = 150,  event = { 'dmgDelay', -2, 'dmgWrong', 1 },                   name = "The Hotel",           MSshuffle = 1 },
    { top = 300,  event = { 'dmgDelay', -2, 'dmgCycle', -.5 },                 name = "The Casino" },
    { top = 450,  event = { 'dmgDelay', -1, 'dmgCycle', -.5 },                 name = "The Arena" },
    { top = 650,  event = { 'dmgDelay', -1, 'dmgCycle', -.5, 'dmgWrong', 1 },  name = "The Museum",          MSshuffle = 2 },
    { top = 850,  event = { 'dmgDelay', -1, 'dmgTime', 1, 'maxQuestSize', 1 }, name = "Abandoned Offices" },
    { top = 1100, event = { 'dmgDelay', -1, 'dmgCycle', -.5 },                 name = "The Laboratory",      MSshuffle = 3 },
    { top = 1350, event = { 'dmgDelay', -1, 'dmgCycle', -.5 },                 name = "The Core" },
    { top = 1650, event = { 'dmgDelay', -.5, 'dmgWrong', 1 },                  name = "Corruption",          MSshuffle = 4 },
    { top = 1e99, event = { 'dmgDelay', -.5, 'dmgCycle', -.5, 'dmgTime', 1 },  name = "Platform of the Gods" },
    -- Initial: Delay=15. Cycle=5, Wrong=1
    -- Total: Delay-10, Cycle-3, Wrong+4
}

Fatigue = {
    normal = {
        { time = 90,   event = { 'extraQuestBase', .2 } },
        { time = 180,  event = { 'extraQuestBase', .2 } },
        { time = 240,  event = { 'extraQuestBase', .2 } },
        { time = 300,  event = { 'dmgTimeMul', -.1 },                                         text = "FATIGUE SETS IN_",          desc = "TimerSpeed++" },
        { time = 330,  event = { 'dmgCycle', -.5, 'dmgWrong', 1 },                            text = "YOUR BODY GROWS WEAK_",     desc = "DmgCycle--   Damage++" },
        { time = 360,  event = { 'dmgTimeMul', -.1, 'dmgHeal', -1 },                          text = "ALL SENSES BLUR TOGETHER_", desc = "TimerSpeed++   Heal--" },
        { time = 390,  event = { 'dmgTimeMul', -.1, 'dmgWrong', 1 },                          text = "YOUR CONSCIOUSNESS FADES_", desc = "TimerSpeed++   Damage++" },
        { time = 420,  event = { 'dmgTimeMul', -.2, 'dmgCycle', -.5 },                        text = "THIS IS THE END.",          desc = "TimerSpeed++   DmgCycle--" },
        { time = 480,  event = { 'maxQuestSize', 1, 'extraQuestVar', 1, 'atkBufferCap', 18 }, text = "FAREWELL.",                 desc = "QuestDifficulty++++++" },
        { time = 1e99, text = "" }, -- Total: dmgTimeMul-50%, Cycle-1, Wrong+2
    },
    rEX = {
        { time = 90,   event = { 'extraQuestBase', .2 } },
        { time = 180,  event = { 'extraQuestBase', .2 } },
        { time = 240,  event = { 'extraQuestBase', .2 } },
        { time = 240,  event = { 'dmgTimeMul', -.2 },                 text = "YOUR POWER SLIPS_",               desc = "TimerSpeed++" },
        { time = 270,  event = { 'dmgWrong', 2 },                     text = "WHISPERS OF DISCONTENT SPREAD_",  desc = "Damage++" },
        { time = 300,  event = { 'dmgCycle', -1 },                    text = "PROTESTERS LINE THE STREETS_",    desc = "DmgCycle--" },
        { time = 330,  event = { 'dmgTimeMul', -.2, 'dmgWrong', 2, }, text = "YOUR CLOSEST ALLIES DEFECT_",     desc = "TimerSpeed++   Damage++" },
        { time = 360,  event = { 'dmgTimeMul', -.2, 'dmgHeal', -1 },  text = "PARANOIA CLOUDS YOUR JUDGEMENT_", desc = "TimerSpeed++   Heal--" },
        { time = 390,  event = { 'dmgCycle', -.5, 'dmgWrong', 1 },    text = "THE REVOLUTION HAS BEGUN_",       desc = "DmgCycle--   Damage++" },
        { time = 420,  event = { 'dmgTimeMul', -.3 },                 text = "THE END OF AN ERA.",              desc = "TimerSpeed++++" },
        { time = 1e99, text = "" }, -- Total: dmgTimeMul-90%, Cycle-1, Wrong+5
    },
    rDP = {
        { time = 20,   event = { 'dmgHeal', -1 }, --[[ 2 ]]    text = "YOUR PASSION FADES_",                        desc = "Heal-" },
        { time = 40,   event = { 'dmgHeal', -.5 }, --[[ 1.5 ]] text = "THEIR REPLIES BECOME LESS ENGAGED_",         desc = "Heal--" },
        { time = 60,   event = { 'dmgHeal', -.5 }, --[[ 1 ]]   text = "YOU FEEL NEGLECTED_",                        desc = "Heal---" },
        { time = 80,   event = { 'dmgHeal', 1 }, --[[ 2 ]]     text = "THEY SUCCESSFULLY APOLOGIZE_?",              desc = "Heal+",         color = 'lO' },
        { time = 90,   event = { 'extraQuestBase', .2 } },
        { time = 100,  event = { 'dmgHeal', 1 }, --[[ 3 ]]     text = "THINGS ARE BACK TO HOW THEY USED TO BE_!",   desc = "Heal+++",       color = 'lO' },
        { time = 120,  event = { 'dmgHeal', -1 }, --[[ 2 ]]    text = "MINOR ISSUES BECOME LARGE CONFLICTS_",       desc = "Heal--" },
        { time = 140,  event = { 'dmgHeal', -1 }, --[[ 1 ]]    text = "YOU BLAME THEM FOR YOUR OWN PROBLEMS_",      desc = "Heal---" },
        { time = 160,  event = { 'reviveCount', 3 },           text = "THEY WOULD RATHER SPEND TIME ALONE_",        desc = "Revive++" },
        { time = 180,  event = { 'extraQuestBase', .2 } },
        { time = 180,  event = { 'dmgHeal', 1.5 }, --[[ 2.5 ]] text = "YOU PROMISE TO CHANGE_",                     desc = "Heal++",        color = 'lO' },
        { time = 200,  event = { 'dmgTimeMul', -.2 },          text = "PROMISES ARE BROKEN_",                       desc = "TimerSpeed++" },
        { time = 220,  event = { 'dmgHeal', -.5 }, --[[ 2 ]]   text = "CONVERSATIONS DEVOLVE TO SHOUTING MATCHES_", desc = "Heal---" },
        { time = 240,  event = { 'extraQuestBase', .2 } },
        { time = 240,  event = { 'dmgHeal', -.5 }, --[[ 1.5 ]] text = "ALL TRUST HAS WITHERED AWAY_",               desc = "Heal--" },
        { time = 260,  event = { 'dmgHeal', -.5 }, --[[ 1 ]]   text = "THEY SET AN ULTIMATUM_",                     desc = "Heal--" },
        { time = 280,  event = { 'dmgHeal', -.5 }, --[[ .5 ]]  text = "YOU CAN'T BE BOTHERED ANYMORE_",             desc = "Heal--" },
        { time = 300,  event = { 'dmgWrong', 2 },              text = "ONE LAST PAINFUL ARGUMENT_",                 desc = "Dmg+" },
        { time = 320,  event = { 'noRevive', 1 },              text = "GOODBYE.",                                   desc = "NO REVIVE" },
        { time = 360,  event = { 'dmgHeal', 1 }, --[[ 1.5 ]]   text = "\"I MISS YOU\"",                             desc = "Heal+++",       color = 'lO' },
        { time = 380,  event = { 'dmgHeal', 1 }, --[[ 2.5 ]]   text = "MAYBE IT CAN STILL WORK_?",                  desc = "Heal+",         color = 'lO' },
        { time = 400,  event = { 'dmgTimeMul', -.5 },          text = "GOODBYE.",                                   desc = "TimerSpeed++++" },
        { time = 1e99, text = "" }, -- Total: dmgTimeMul-70%
    },
}
-- My formatter doesn't work if there's "…" inside
for _, f in next, Fatigue do for _, v in next, f do if v.text then v.text = v.text:gsub("_", "…") end end end

local function rndMod(t)
    local d = ModData.deck[math.random(9)].id
    t.prompt = t.prompt:repD(d)
    t.text = t.text:repD(ModData.adj[d])
    t.short = t.short:repD(d)
end
local function f5() return GAME.floor <= 5 end
local function F6() return GAME.floor >= 6 end
local function F9() return GAME.floor >= 9 end

---@class Prompt
---@field rank number[]
---@field prompt string
---@field target number
---@field short string
---@field text string
---@field cond? fun():boolean
---@field init? fun(t:Prompt)

---@type Prompt[]
RevivePrompts = {
    { rank = { 1, 2 }, prompt = 'activate',             target = 30,  short = "Activate 30",             text = "Activate 30 cards" },
    { rank = { 3, 4 }, prompt = 'activate',             target = 80,  short = "Activate 80",             text = "Activate 80 cards" },
    { rank = { 2, 2 }, prompt = 'cancel',               target = 40,  short = "Cancel 40",               text = "Cancel 40 cards" },
    { rank = { 3, 4 }, prompt = 'cancel',               target = 100, short = "Cancel 100",              text = "Cancel 100 cards" },
    { rank = { 1, 2 }, prompt = 'flip',                 target = 50,  short = "Flip 50",                 text = "Flip 50 cards" },
    { rank = { 3, 4 }, prompt = 'flip',                 target = 120, short = "Flip 120",                text = "Flip 120 cards" },
    { rank = { 5, 6 }, prompt = 'flip',                 target = 300, short = "Flip 300",                text = "Flip 300 cards" },
    { rank = { 1, 2 }, prompt = 'flip_single',          target = 10,  short = "Flip single 10",          text = "Flip a single card\n10 times in a row" },
    { rank = { 2, 4 }, prompt = 'flip_single',          target = 20,  short = "Flip single 20",          text = "Flip a single card\n20 times in a row" },
    { rank = { 1, 2 }, prompt = 'commit',               target = 6,   short = "Commit 6x",               text = "Commit 6 times" },
    { rank = { 2, 3 }, prompt = 'commit',               target = 15,  short = "Commit 15x",              text = "Commit 15 times" },
    { rank = { 3, 5 }, prompt = 'commit',               target = 30,  short = "Commit 30x",              text = "Commit 30 times" },
    { rank = { 1, 2 }, prompt = 'commit_$1',            target = 2,   short = "Commit $1 2x",            text = "Commit 2 times\nwith $1",                     init = rndMod },
    { rank = { 3, 4 }, prompt = 'commit_$1',            target = 4,   short = "Commit $1 4x",            text = "Commit 4 times\nwith $1",                     init = rndMod },
    { rank = { 2, 4 }, prompt = 'commit_$1_row',        target = 2,   short = "2 Chain with $1",         text = "Commit 2 times\nwith $1 in a row",            init = rndMod },
    { rank = { 3, 6 }, prompt = 'commit_$1_row',        target = 3,   short = "3 Chain with $1",         text = "Commit 3 times\nwith $1 in a row",            init = rndMod },
    { rank = { 1, 3 }, prompt = 'commit_no_$1_row',     target = 2,   short = "2 chain without $1",      text = "Commit 2 times\nwithout $1 in a row",         init = rndMod },
    { rank = { 3, 5 }, prompt = 'commit_no_$1_row',     target = 3,   short = "3 chain without $1",      text = "Commit 3 times\nwithout $1 in a row",         init = rndMod },
    { rank = { 1, 2 }, prompt = 'commit_0',             target = 2,   short = "Commit NOTHING 2x",       text = "Commit NOTHING\n2 times" },
    { rank = { 2, 4 }, prompt = 'commit_0',             target = 5,   short = "Commit NOTHING 5x",       text = "Commit NOTHING\n5 times" },
    { rank = { 4, 6 }, prompt = 'commit_0',             target = 8,   short = "Commit NOTHING 8x",       text = "Commit NOTHING\n8 times" },
    { rank = { 1, 3 }, prompt = 'commit_0_row',         target = 3,   short = "3x Spam commit",          text = "Commit NOTHING\n3 times in a row" },
    { rank = { 3, 5 }, prompt = 'commit_no_conn',       target = 1,   short = "Commit no consec",        text = "Commit without consecutive cards",            cond = F6 },
    { rank = { 1, 4 }, prompt = 'commit_conn_2',        target = 1,   short = "Commit 2 consec",         text = "Commit with 2 consecutive cards",             cond = f5 },
    { rank = { 2, 4 }, prompt = 'commit_conn_3',        target = 1,   short = "Commit 3 consec",         text = "Commit with 3 consecutive cards",             cond = f5 },
    { rank = { 3, 5 }, prompt = 'commit_conn_4',        target = 1,   short = "Commit 4 consec",         text = "Commit with 4 consecutive cards" },
    { rank = { 3, 5 }, prompt = 'commit_swamp_l',       target = 1,   short = "SWAMP WATER LITE",        text = "Commit SWAMP WATER LITE" },
    { rank = { 4, 6 }, prompt = 'commit_swamp',         target = 1,   short = "SWAMP WATER",             text = "Commit SWAMP WATER" },
    { rank = { 3, 6 }, prompt = 'commit_reversed',      target = 1,   short = "Commit inversed",         text = "Commit all cards\nwhich are not requested" },
    { rank = { 1, 4 }, prompt = 'commit_1card',         target = 3,   short = "Commit 1 cards 3x",       text = "Commit 3 times with\n1 card on first commit" },
    { rank = { 2, 5 }, prompt = 'commit_2card',         target = 4,   short = "Commit 2 cards 4x",       text = "Commit 4 times with\n2 cards on first commit" },
    { rank = { 3, 6 }, prompt = 'commit_3card',         target = 5,   short = "Commit 3 cards 5x",       text = "Commit 5 times with\n3 cards on first commit" },
    { rank = { 4, 6 }, prompt = 'commit_4card',         target = 4,   short = "Commit 4 cards 4x",       text = "Commit 4 times with\n4 cards on first commit" },
    { rank = { 5, 6 }, prompt = 'commit_5card',         target = 3,   short = "Commit 5 cards 3x",       text = "Commit 3 times with\n5 cards on first commit" },
    { rank = { 1, 4 }, prompt = 'pass',                 target = 10,  short = "Pass 10",                 text = "Pass 10 times" },
    { rank = { 5, 6 }, prompt = 'pass',                 target = 20,  short = "Pass 20",                 text = "Pass 20 times" },
    { rank = { 2, 5 }, prompt = 'pass_$1',              target = 2,   short = "Pass 2 with $1",          text = "Pass 2 times\nwith $1",                       init = rndMod },
    { rank = { 3, 5 }, prompt = 'pass_$1',              target = 3,   short = "Pass 3 with $1",          text = "Pass 3 times\nwith $1",                       init = rndMod },
    { rank = { 4, 6 }, prompt = 'pass_$1',              target = 4,   short = "Pass 4 with $1",          text = "Pass 4 times\nwith $1",                       init = rndMod },
    { rank = { 2, 4 }, prompt = 'pass_perfect',         target = 6,   short = "6x perf",                 text = "Pass 6 times perfectly" },
    { rank = { 5, 6 }, prompt = 'pass_perfect',         target = 12,  short = "12x perf",                text = "Pass 12 times perfectly" },
    { rank = { 2, 4 }, prompt = 'pass_imperfect',       target = 6,   short = "6x im-perf",              text = "Pass 6 times imperfectly" },
    { rank = { 5, 6 }, prompt = 'pass_imperfect',       target = 12,  short = "12x im-perf",             text = "Pass 12 times imperfectly" },
    { rank = { 4, 5 }, prompt = 'pass_imperfect_row',   target = 3,   short = "3x chain im-perf",        text = "Pass 3 times\nimperfectly in a row" },
    { rank = { 5, 6 }, prompt = 'pass_imperfect_row',   target = 8,   short = "8x chain im-perf",        text = "Pass 8 times\nimperfectly in a row" },
    { rank = { 2, 4 }, prompt = 'pass_perfect_row',     target = 4,   short = "B2B x 4",                 text = "Reach B2B x 4" },
    { rank = { 3, 5 }, prompt = 'pass_perfect_row',     target = 6,   short = "B2B x 6",                 text = "Reach B2B x 6" },
    { rank = { 4, 5 }, prompt = 'pass_perfect_row',     target = 8,   short = "B2B x 8",                 text = "Reach B2B x 8" },
    { rank = { 4, 6 }, prompt = 'pass_perfect_row',     target = 10,  short = "B2B x 10",                text = "Reach B2B x 10" },
    { rank = { 2, 3 }, prompt = 'pass_second',          target = 4,   short = "2nd quest 4x",            text = "Pass the second\nquest 4 times" },
    { rank = { 3, 4 }, prompt = 'pass_second',          target = 8,   short = "2nd quest 8x",            text = "Pass the second\nquest 8 times" },
    { rank = { 4, 5 }, prompt = 'pass_second',          target = 12,  short = "2nd quest 12x",           text = "Pass the second\nquest 12 times" },
    { rank = { 2, 4 }, prompt = 'b2b_break_4',          target = 1,   short = "Break B2B 4x",            text = "Break B2B x 4" },
    { rank = { 3, 4 }, prompt = 'b2b_break_6',          target = 1,   short = "Break B2B 6x",            text = "Break B2B x 6" },
    { rank = { 4, 5 }, prompt = 'b2b_break_8',          target = 1,   short = "Break B2B 8x",            text = "Break B2B x 8" },
    { rank = { 4, 6 }, prompt = 'b2b_break_10',         target = 1,   short = "Break B2B 10x",           text = "Break B2B x 10" },
    { rank = { 4, 6 }, prompt = 'b2b_break_windup',     target = 1,   short = "Break B2B at a windup",   text = "Break B2B at a windup",                       cond = F9 },
    { rank = { 5, 6 }, prompt = 'b2b_break_windup3',    target = 1,   short = "Break B2B at a windup3+", text = "Break B2B at\na lv.3+ windup",                cond = F9 },
    { rank = { 1, 3 }, prompt = 'heal',                 target = 8,   short = "Heal 8 HP",               text = "Heal 8 HP" },
    { rank = { 2, 4 }, prompt = 'heal',                 target = 20,  short = "Heal 20 HP",              text = "Heal 20 HP" },
    { rank = { 1, 2 }, prompt = 'send',                 target = 6,   short = "Send 6",                  text = "Send 6 attacks" },
    { rank = { 3, 4 }, prompt = 'send',                 target = 20,  short = "Send 20",                 text = "Send 20 attacks" },
    { rank = { 5, 6 }, prompt = 'send',                 target = 40,  short = "Send 40",                 text = "Send 40 attacks" },
    { rank = { 3, 4 }, prompt = 'pass_windup',          target = 1,   short = "Windup",                  text = "Pass a windup",                               cond = F9 },
    { rank = { 3, 5 }, prompt = 'pass_windup3',         target = 1,   short = "Windup3+",                text = "Pass a lv.3+ windup",                         cond = F9 },
    { rank = { 5, 5 }, prompt = 'pass_windup_inb2b',    target = 1,   short = "Windup with B2B",         text = "Pass a windup\nduring one B2B charge",        cond = F9 },
    { rank = { 4, 5 }, prompt = 'pass_windup',          target = 4,   short = "Windup x 4",              text = "Pass 4 windups",                              cond = F9 },
    { rank = { 4, 4 }, prompt = 'pass_windup_perfect',  target = 1,   short = "Windup perf",             text = "Pass a windup\nperfectly",                    cond = F9 },
    { rank = { 6, 6 }, prompt = 'pass_windup_inb2b',    target = 3,   short = "Windup x 3 with B2B",     text = "Pass 4 windups\nduring a B2B charge",         cond = F9 },
    { rank = { 5, 5 }, prompt = 'pass_windup_perfect',  target = 4,   short = "Windup perf x 4",         text = "Pass 4 windups\nperfectly",                   cond = F9 },
    { rank = { 5, 5 }, prompt = 'pass_windup3_perfect', target = 1,   short = "Windup3+ perf",           text = "Pass a lv.3+\nwindup perfectly",              cond = F9 },
    { rank = { 6, 6 }, prompt = 'pass_windup3_perfect', target = 4,   short = "Windup3+ perf x 4",       text = "Pass 4 lv.3+\nwindups perfectly",             cond = F9 },
    { rank = { 2, 2 }, prompt = 'dmg_time',             target = 4,   short = "Take Dmg 4x",             text = "Take damage 4 times" },
    { rank = { 3, 3 }, prompt = 'dmg_time',             target = 8,   short = "Take Dmg 8x",             text = "Take damage 8 times" },
    { rank = { 2, 4 }, prompt = 'dmg_amount',           target = 10,  short = "Lose 10 HP",              text = "Take 10 damage total" },
    { rank = { 4, 6 }, prompt = 'dmg_amount',           target = 20,  short = "Lose 20 HP",              text = "Take 20 damage total" },
    { rank = { 3, 4 }, prompt = 'timedmg_time',         target = 2,   short = "Take Time Dmg 2x",        text = "Take time damage 2 times",                    cond = F6 },
    { rank = { 5, 6 }, prompt = 'timedmg_time',         target = 4,   short = "Take Time Dmg 4x",        text = "Take time damage 4 times",                    cond = F6 },
    { rank = { 4, 6 }, prompt = 'keep_health_safe',     target = 8,   short = "Safe HP 8s",              text = "Keep HP safe for\n8 seconds",                 cond = F6 },
    { rank = { 4, 5 }, prompt = 'keep_health_danger',   target = 3,   short = "Danger HP 3s",            text = "Keep HP in danger\nfor 3 seconds",            cond = F6 },
    { rank = { 2, 5 }, prompt = 'keep_no_mouse',        target = 4,   short = "No mouse 4s",             text = "Don't touch mouse\nfor 4 seconds",            cond = f5 },
    { rank = { 2, 4 }, prompt = 'keep_no_commit',       target = 6,   short = "No commit 6s",            text = "Don't commit\nfor 6 seconds",                 cond = f5 },
    { rank = { 3, 6 }, prompt = 'keep_no_cancel',       target = 8,   short = "No cancel 8s",            text = "Don't cancel\nfor 8 seconds" },
    { rank = { 2, 5 }, prompt = 'keep_no_keyboard',     target = 10,  short = "No keyboard 10s",         text = "Don't touch keyboard\nfor 10 seconds",        cond = F6 },
    { rank = { 3, 5 }, prompt = 'keep_no_perfect',      target = 12,  short = "No perfect 12s",          text = "Don't perfect\nfor 12 seconds" },
    { rank = { 4, 6 }, prompt = 'keep_no_imperfect',    target = 14,  short = "No imperfect 14s",        text = "Don't imperfect\nfor 14 seconds",             cond = F6 },
    { rank = { 3, 5 }, prompt = 'keep_no_reset',        target = 16,  short = "No reset 16s",            text = "Don't reset\nfor 16 seconds" },
}
