---@type Zenitha.Scene
local scene = {}

local t1, t2 = .26, .42

function scene.load()
    love.keyboard.setKeyRepeat(false)
end

scene.keyDown = TRUE

function scene.update(dt)
    dt = math.min(dt, 1 / 26)
    if TASK.lock('init') then
    elseif t1 > 0 then
        t1 = t1 - dt
        if t1 <= 0 then
            TEXTS.load:set("GETTING READY TO SPECTATE...")
            BGM.setMaxSources(42)
            BGM.load(FILE.load('module/bgm_data.lua', '-luaon'))

            SFX.load('assets/sfx.ogg', FILE.load('module/sfx_data.lua', '-luaon'))
            -- fallback sfx
            
            SFX.load('menuback', 'assets/sfx/menuback.wav')
            SFX.load('menuclick', 'assets/sfx/menuclick.wav')
            SFX.load('menuconfirm', 'assets/sfx/menuconfirm.wav')
            SFX.load('menuhit1', 'assets/sfx/menuhit1.wav')
            --SFX.load('menuhit2', 'assets/sfx/menuhit2.wav')
            --SFX.load('menuhit3', 'assets/sfx/menuhit3.wav')
            SFX.load('menuhover', 'assets/sfx/menuhover.wav')
            SFX.load('menutap', 'assets/sfx/menutap.wav')
            
            SFX.load('card_select', 'assets/sfx/card_select.wav')
            SFX.load('card_slide_1', 'assets/sfx/card_slide_1.wav')
            SFX.load('card_slide_2', 'assets/sfx/card_slide_2.wav')
            SFX.load('card_slide_3', 'assets/sfx/card_slide_3.wav')
            SFX.load('card_slide_4', 'assets/sfx/card_slide_4.wav')
            SFX.load('card_tone_expert', 'assets/sfx/card_tone_expert.wav')
            SFX.load('card_tone_nohold', 'assets/sfx/card_tone_nohold.wav')
            SFX.load('card_tone_messy', 'assets/sfx/card_tone_messy.wav')
            SFX.load('card_tone_gravity', 'assets/sfx/card_tone_gravity.wav')
            SFX.load('card_tone_volatile', 'assets/sfx/card_tone_volatile.wav')
            SFX.load('card_tone_doublehole', 'assets/sfx/card_tone_doublehole.wav')
            SFX.load('card_tone_invisible', 'assets/sfx/card_tone_invisible.wav')
            SFX.load('card_tone_allspin', 'assets/sfx/card_tone_allspin.wav')
            SFX.load('card_tone_duo', 'assets/sfx/card_tone_duo.wav')
            
            SFX.load('card_select_reverse', 'assets/sfx/card_select_reverse.wav')
            SFX.load('card_reverse_impact', 'assets/sfx/card_reverse_impact.wav')
            SFX.load('card_tone_expert_reverse', 'assets/sfx/card_tone_expert_reverse.wav')
            SFX.load('card_tone_nohold_reverse', 'assets/sfx/card_tone_nohold_reverse.wav')
            SFX.load('card_tone_messy_reverse', 'assets/sfx/card_tone_messy_reverse.wav')
            SFX.load('card_tone_gravity_reverse', 'assets/sfx/card_tone_gravity_reverse.wav')
            SFX.load('card_tone_volatile_reverse', 'assets/sfx/card_tone_volatile_reverse.wav')
            SFX.load('card_tone_doublehole_reverse', 'assets/sfx/card_tone_doublehole_reverse.wav')
            SFX.load('card_tone_invisible_reverse', 'assets/sfx/card_tone_invisible_reverse.wav')
            SFX.load('card_tone_allspin_reverse', 'assets/sfx/card_tone_allspin_reverse.wav')
            SFX.load('card_tone_duo_reverse', 'assets/sfx/card_tone_duo_reverse.wav')

            SFX.load('garbagewindup_1', 'assets/sfx/garbagewindup_1.wav')
            SFX.load('garbagewindup_2', 'assets/sfx/garbagewindup_2.wav')
            SFX.load('garbagewindup_3', 'assets/sfx/garbagewindup_3.wav')
            SFX.load('garbagewindup_4', 'assets/sfx/garbagewindup_4.wav')
            SFX.load('garbagewindup_5', 'assets/sfx/garbagewindup_5.wav')
            
            SFX.load('zenith_start', 'assets/sfx/zenith_start.wav')
            SFX.load('zenith_start_duo', 'assets/sfx/zenith_start_duo.wav')
            SFX.load('zenith_levelup_c', 'assets/sfx/zenith_levelup_c.wav')
            SFX.load('zenith_levelup_b', 'assets/sfx/zenith_levelup_b.wav')
            SFX.load('zenith_levelup_a', 'assets/sfx/zenith_levelup_a.wav')
            SFX.load('zenith_levelup_fsharp', 'assets/sfx/zenith_levelup_fsharp.wav')
            SFX.load('zenith_levelup_e', 'assets/sfx/zenith_levelup_e.wav')
            SFX.load('zenith_levelup_ahalfsharp', 'assets/sfx/zenith_levelup_ahalfsharp.wav')
            SFX.load('zenith_levelup_g', 'assets/sfx/zenith_levelup_g.wav')
            SFX.load('zenith_speedrun_start', 'assets/sfx/zenith_speedrun_start.wav')
            SFX.load('zenith_split_cleared', 'assets/sfx/zenith_split_cleared.wav')
            -- SFX.load('zenith_split_missed', 'assets/sfx/zenith_split_missed.wav')
            SFX.load('zenith_speedrun_end', 'assets/sfx/zenith_speedrun_end.wav')
            
            SFX.load('speed_tick_1', 'assets/sfx/speed_tick_1.wav')
            SFX.load('speed_tick_2', 'assets/sfx/speed_tick_2.wav')
            SFX.load('speed_tick_3', 'assets/sfx/speed_tick_3.wav')
            SFX.load('speed_tick_4', 'assets/sfx/speed_tick_4.wav')
            SFX.load('speed_tick_whirl', 'assets/sfx/speed_tick_whirl.wav')
            SFX.load('speed_down', 'assets/sfx/speed_down.wav')
            SFX.load('speed_up_1', 'assets/sfx/speed_up_1.wav')
            SFX.load('speed_up_2', 'assets/sfx/speed_up_2.wav')
            SFX.load('speed_up_3', 'assets/sfx/speed_up_3.wav')
            SFX.load('speed_up_4', 'assets/sfx/speed_up_4.wav')
            
            SFX.load('wound', 'assets/sfx/wound.wav')
            SFX.load('wound_repel', 'assets/sfx/wound_repel.wav')
            
            SFX.load('z', 'assets/sfx/z.wav')
            SFX.load('s', 'assets/sfx/s.wav')
            SFX.load('j', 'assets/sfx/j.wav')
            SFX.load('l', 'assets/sfx/l.wav')
            SFX.load('t', 'assets/sfx/t.wav')
            SFX.load('o', 'assets/sfx/o.wav')
            SFX.load('i', 'assets/sfx/i.wav')

            SFX.load('move', 'assets/sfx/move.wav')
            SFX.load('rotate', 'assets/sfx/rotate.wav')
            SFX.load('spin', 'assets/sfx/spin.wav')
            -- SFX.load('spinend', 'assets/sfx/spinend.wav')
            SFX.load('floor', 'assets/sfx/floor.wav')
            -- SFX.load('hit', 'assets/sfx/hit.wav')
            -- SFX.load('sidehit', 'assets/sfx/sidehit.wav')
            -- SFX.load('softdrop', 'assets/sfx/softdrop.wav')
            SFX.load('harddrop', 'assets/sfx/harddrop.wav')
            SFX.load('hold', 'assets/sfx/hold.wav')
            SFX.load('irs', 'assets/sfx/irs.wav')
            -- SFX.load('ihs', 'assets/sfx/ihs.wav')
            SFX.load('finessefault', 'assets/sfx/finessefault.wav')
            
            SFX.load('clutch', 'assets/sfx/clutch.wav')
            SFX.load('clearline', 'assets/sfx/clearline.wav')
            SFX.load('clearquad', 'assets/sfx/clearquad.wav')
            SFX.load('clearspin', 'assets/sfx/clearspin.wav')
            SFX.load('clearbtb', 'assets/sfx/clearbtb.wav')
            SFX.load('allclear', 'assets/sfx/allclear.wav')
            SFX.load('bombdetonate', 'assets/sfx/bombdetonate.wav')
            
            SFX.load('combo_1', 'assets/sfx/combo_1.wav')
            SFX.load('combo_2', 'assets/sfx/combo_2.wav')
            SFX.load('combo_3', 'assets/sfx/combo_3.wav')
            SFX.load('combo_4', 'assets/sfx/combo_4.wav')
            -- SFX.load('combo_5', 'assets/sfx/combo_5.wav')
            -- SFX.load('combo_6', 'assets/sfx/combo_6.wav')
            -- SFX.load('combo_7', 'assets/sfx/combo_7.wav')
            -- SFX.load('combo_8', 'assets/sfx/combo_8.wav')
            -- SFX.load('combo_9', 'assets/sfx/combo_9.wav')
            -- SFX.load('combo_10', 'assets/sfx/combo_10.wav')
            -- SFX.load('combo_11', 'assets/sfx/combo_11.wav')
            -- SFX.load('combo_12', 'assets/sfx/combo_12.wav')
            -- SFX.load('combo_13', 'assets/sfx/combo_13.wav')
            -- SFX.load('combo_14', 'assets/sfx/combo_14.wav')
            -- SFX.load('combo_15', 'assets/sfx/combo_15.wav')
            -- SFX.load('combo_16', 'assets/sfx/combo_16.wav')
            -- SFX.load('combo_1_power', 'assets/sfx/combo_1_power.wav')
            -- SFX.load('combo_2_power', 'assets/sfx/combo_2_power.wav')
            -- SFX.load('combo_3_power', 'assets/sfx/combo_3_power.wav')
            -- SFX.load('combo_4_power', 'assets/sfx/combo_4_power.wav')
            -- SFX.load('combo_5_power', 'assets/sfx/combo_5_power.wav')
            -- SFX.load('combo_6_power', 'assets/sfx/combo_6_power.wav')
            -- SFX.load('combo_7_power', 'assets/sfx/combo_7_power.wav')
            -- SFX.load('combo_8_power', 'assets/sfx/combo_8_power.wav')
            -- SFX.load('combo_9_power', 'assets/sfx/combo_9_power.wav')
            -- SFX.load('combo_10_power', 'assets/sfx/combo_10_power.wav')
            -- SFX.load('combo_11_power', 'assets/sfx/combo_11_power.wav')
            -- SFX.load('combo_12_power', 'assets/sfx/combo_12_power.wav')
            -- SFX.load('combo_13_power', 'assets/sfx/combo_13_power.wav')
            -- SFX.load('combo_14_power', 'assets/sfx/combo_14_power.wav')
            -- SFX.load('combo_15_power', 'assets/sfx/combo_15_power.wav')
            -- SFX.load('combo_16_power', 'assets/sfx/combo_16_power.wav')
            -- SFX.load('combobreak', 'assets/sfx/combobreak.wav')
            
            -- SFX.load('btb_1', 'assets/sfx/btb_1.wav')
            -- SFX.load('btb_2', 'assets/sfx/btb_2.wav')
            -- SFX.load('btb_3', 'assets/sfx/btb_3.wav')
            SFX.load('btb_break', 'assets/sfx/btb_break.wav')
            SFX.load('b2bcharge_start', 'assets/sfx/b2bcharge_start.wav')
            SFX.load('b2bcharge_danger', 'assets/sfx/b2bcharge_danger.wav')
            SFX.load('b2bcharge_1', 'assets/sfx/b2bcharge_1.wav')
            SFX.load('b2bcharge_2', 'assets/sfx/b2bcharge_2.wav')
            SFX.load('b2bcharge_3', 'assets/sfx/b2bcharge_3.wav')
            SFX.load('b2bcharge_4', 'assets/sfx/b2bcharge_4.wav')
            SFX.load('b2bcharge_blast_1', 'assets/sfx/b2bcharge_blast_1.wav')
            SFX.load('b2bcharge_blast_2', 'assets/sfx/b2bcharge_blast_2.wav')
            SFX.load('b2bcharge_blast_3', 'assets/sfx/b2bcharge_blast_3.wav')
            SFX.load('b2bcharge_blast_4', 'assets/sfx/b2bcharge_blast_4.wav')
            SFX.load('b2bcharge_distance_1', 'assets/sfx/b2bcharge_distance_1.wav')
            SFX.load('b2bcharge_distance_2', 'assets/sfx/b2bcharge_distance_2.wav')
            SFX.load('b2bcharge_distance_3', 'assets/sfx/b2bcharge_distance_3.wav')
            SFX.load('thunder1', 'assets/sfx/thunder1.wav')
            SFX.load('thunder2', 'assets/sfx/thunder2.wav')
            SFX.load('thunder3', 'assets/sfx/thunder3.wav')
            SFX.load('thunder4', 'assets/sfx/thunder4.wav')
            SFX.load('thunder5', 'assets/sfx/thunder5.wav')
            SFX.load('thunder6', 'assets/sfx/thunder6.wav')
            
            SFX.load('inject', 'assets/sfx/inject.wav')
            -- SFX.load('impact', 'assets/sfx/impact.wav')
            -- SFX.load('offset', 'assets/sfx/offset.wav')
            
            -- SFX.load('countdown5', 'assets/sfx/countdown5.wav')
            -- SFX.load('countdown4', 'assets/sfx/countdown4.wav')
            -- SFX.load('countdown3', 'assets/sfx/countdown3.wav')
            -- SFX.load('countdown2', 'assets/sfx/countdown2.wav')
            -- SFX.load('countdown1', 'assets/sfx/countdown1.wav')
            SFX.load('rsg_go', 'assets/sfx/rsg_go.wav')
            -- SFX.load('rsg', 'assets/sfx/rsg.wav')
            -- SFX.load('go', 'assets/sfx/go.wav')
            -- SFX.load('undo', 'assets/sfx/undo.wav')
            -- SFX.load('redo', 'assets/sfx/redo.wav')
            -- SFX.load('target', 'assets/sfx/target.wav')
            SFX.load('counter', 'assets/sfx/counter.wav')
            -- SFX.load('exchange', 'assets/sfx/exchange.wav')
            -- SFX.load('collapse', 'assets/sfx/collapse.wav')
            -- SFX.load('fire', 'assets/sfx/fire.wav')
            SFX.load('warp', 'assets/sfx/warp.wav')
            -- SFX.load('finish', 'assets/sfx/finish.wav')
            -- SFX.load('death', 'assets/sfx/death.wav')
            SFX.load('elim', 'assets/sfx/elim.wav')
            -- SFX.load('levelup', 'assets/sfx/levelup.wav')
            SFX.load('shatter', 'assets/sfx/shatter.wav')
            SFX.load('hyperalert', 'assets/sfx/hyperalert.wav')
            SFX.load('topout', 'assets/sfx/topout.wav')
            SFX.load('losestock', 'assets/sfx/losestock.wav')
            -- SFX.load('gameover', 'assets/sfx/gameover.wav')
            
            SFX.load('applause', 'assets/sfx/applause.wav')
            SFX.load('victory', 'assets/sfx/victory.wav')
            -- SFX.load('failure', 'assets/sfx/failure.wav')
            SFX.load('personalbest', 'assets/sfx/personalbest.wav')
            SFX.load('worldrecord', 'assets/sfx/worldrecord.wav')
            -- SFX.load('ranklower', 'assets/sfx/ranklower.wav')
            -- SFX.load('rankraise', 'assets/sfx/rankraise.wav')
            -- SFX.load('ratinglower', 'assets/sfx/ratinglower.wav')
            SFX.load('ratingraise', 'assets/sfx/ratingraise.wav')
            
            SFX.load('achievement_1', 'assets/sfx/achievement_1.wav')
            SFX.load('achievement_2', 'assets/sfx/achievement_2.wav')
            SFX.load('achievement_3', 'assets/sfx/achievement_3.wav')
            
            SFX.load('social_notify_major', 'assets/sfx/social_notify_major.wav')
            SFX.load('social_notify_minor', 'assets/sfx/social_notify_minor.wav')
            -- SFX.load('social_open', 'assets/sfx/social_open.wav')
            -- SFX.load('social_close', 'assets/sfx/social_close.wav')
            -- SFX.load('social_open_minor', 'assets/sfx/social_open_minor.wav')
            -- SFX.load('social_close_minor', 'assets/sfx/social_close_minor.wav')
            SFX.load('social_online', 'assets/sfx/social_online.wav')
            SFX.load('social_offline', 'assets/sfx/social_offline.wav')
            SFX.load('social_dm', 'assets/sfx/social_dm.wav')
            -- SFX.load('social_invite', 'assets/sfx/social_invite.wav')
            
            -- SFX.load('boardappear', 'assets/sfx/boardappear.wav')
            SFX.load('boardlock', 'assets/sfx/rank-impact-fail.wav')
            SFX.load('boardlock_clink', 'assets/sfx/boardlock_clink.wav')
            SFX.load('boardlock_fail', 'assets/sfx/rank-impact-fail-d.wav')
            SFX.load('boardlock_clear', 'assets/sfx/rank-impact-pass.wav')
            SFX.load('boardlock_revive', 'assets/sfx/rank-impact-pass-ss.wav')
            SFX.load('party_ready', 'assets/sfx/party_ready.wav')
            SFX.load('cutin_superlobby', 'assets/sfx/cutin_superlobby.wav')
            SFX.load('damage_alert', 'assets/sfx/damage_alert.wav')
            SFX.load('damage_small', 'assets/sfx/damage_small.wav')
            SFX.load('damage_medium', 'assets/sfx/damage_medium.wav')
            SFX.load('damage_large', 'assets/sfx/damage_large.wav')
            SFX.load('detonate1', 'assets/sfx/detonate1.wav')
            SFX.load('detonate2', 'assets/sfx/detonate2.wav')
            SFX.load('detonated', 'assets/sfx/detonated.wav')
            -- SFX.load('garbage_in_small', 'assets/sfx/garbage_in_small.wav')
            -- SFX.load('garbage_in_medium', 'assets/sfx/garbage_in_medium.wav')
            -- SFX.load('garbage_in_large', 'assets/sfx/garbage_in_large.wav')
            -- SFX.load('garbage_out_small', 'assets/sfx/garbage_out_small.wav')
            -- SFX.load('garbage_out_medium', 'assets/sfx/garbage_out_medium.wav')
            -- SFX.load('garbage_out_large', 'assets/sfx/garbage_out_large.wav')
            SFX.load('garbagerise', 'assets/sfx/garbagerise.wav')
            -- SFX.load('garbagesmash', 'assets/sfx/garbagesmash.wav')
            SFX.load('garbagesmash', 'assets/sfx/garbagesmash.wav')
            SFX.load('garbagewindup_1', 'assets/sfx/garbagewindup_1.wav')
            SFX.load('garbagewindup_2', 'assets/sfx/garbagewindup_2.wav')
            SFX.load('garbagewindup_3', 'assets/sfx/garbagewindup_3.wav')
            SFX.load('garbagewindup_4', 'assets/sfx/garbagewindup_4.wav')
            SFX.load('garbagewindup_5', 'assets/sfx/garbagewindup_5.wav')
            -- SFX.load('level1', 'assets/sfx/level1.wav')
            -- SFX.load('level10', 'assets/sfx/level10.wav')
            -- SFX.load('level100', 'assets/sfx/level100.wav')
            -- SFX.load('level500', 'assets/sfx/level500.wav')
            SFX.load('maintenance', 'assets/sfx/maintenance.wav')
            SFX.load('map_change', 'assets/sfx/map_change.wav')
            -- SFX.load('matchintro', 'assets/sfx/matchintro.wav')
            -- SFX.load('mission_free', 'assets/sfx/mission_free.wav')
            -- SFX.load('mission_league', 'assets/sfx/mission_league.wav')
            -- SFX.load('mission_versus', 'assets/sfx/mission_versus.wav')
            -- SFX.load('mission', 'assets/sfx/mission.wav')
            SFX.load('mmstart', 'assets/sfx/mmstart.wav')
            SFX.load('no', 'assets/sfx/no.wav')
            SFX.load('notify', 'assets/sfx/notify.wav')
            -- SFX.load('pause_continue', 'assets/sfx/pause_continue.wav')
            SFX.load('pause_exit', 'assets/sfx/pause_exit.wav')
            -- SFX.load('pause_retry', 'assets/sfx/pause_retry.wav')
            SFX.load('pause_start', 'assets/sfx/pause_start.wav')
            SFX.load('piece_change', 'assets/sfx/piece_change.wav')
            -- SFX.load('protected_small', 'assets/sfx/protected_small.wav')
            -- SFX.load('protected_medium', 'assets/sfx/protected_medium.wav')
            -- SFX.load('protected_large', 'assets/sfx/protected_large.wav')
            -- SFX.load('queue_change', 'assets/sfx/queue_change.wav')
            -- SFX.load('ribbon_off', 'assets/sfx/ribbon_off.wav')
            -- SFX.load('ribbon_on', 'assets/sfx/ribbon_on.wav')
            -- SFX.load('ribbon_tap', 'assets/sfx/ribbon_tap.wav')
            -- SFX.load('ribbon', 'assets/sfx/ribbon.wav')
            -- SFX.load('scoreslide_in', 'assets/sfx/scoreslide_in.wav')
            -- SFX.load('scoreslide_out', 'assets/sfx/scoreslide_out.wav')
            -- SFX.load('se_vol_blip', 'assets/sfx/se_vol_blip.wav')
            -- SFX.load('showscore', 'assets/sfx/showscore.wav')
            SFX.load('staffsilence', 'assets/sfx/staffsilence.wav')
            SFX.load('staffspam', 'assets/sfx/staffspam.wav')
            SFX.load('staffwarning', 'assets/sfx/staffwarning.wav')
            SFX.load('purchase_start', 'assets/sfx/purchase_start.wav')
            SFX.load('supporter', 'assets/sfx/supporter.wav')
            -- SFX.load('timer1', 'assets/sfx/timer1.wav')
            -- SFX.load('timer2', 'assets/sfx/timer2.wav')
            -- SFX.load('userjoin', 'assets/sfx/userjoin.wav')
            -- SFX.load('userleave', 'assets/sfx/userleave.wav')
            SFX.load('warning', 'assets/sfx/warning.wav')

            TASK.new(Daemon_Slow)
            TASK.new(Daemon_Fast)
            ---@diagnostic disable-next-line
            local _ = TEXTURE.panel.glass_a, TEXTURE.panel.glass_b, TEXTURE.panel.throb_a, TEXTURE.panel.throb_b
            for i = 2, 9 do TEXTURE.towerBG[i]:setWrap('mirroredrepeat', 'mirroredrepeat') end
            TEXTURE.towerBG[1]:setWrap('mirroredrepeat', 'clampzero')
            TEXTURE.towerBG[10]:setWrap('mirroredrepeat', 'clampzero')
            TEXTURE.ruler:setWrap('repeat', 'repeat')
            _, _ = TEXTURE.moon, TEXTURE.stars
        end
    elseif t2 > 0 then
        t2 = t2 - dt
        if t2 <= 0 then
            PlayBGM('f0')
            SCN.swapTo('tower')
        end
    end
end

function scene.draw()
    GC.setColor(.2, .2, .2)
    GC.strokeDraw('full', 5, TEXTS.load, 800, 500, 0, 1.6, 2, TEXTS.load:getWidth() / 2, TEXTS.load:getHeight() / 2)
    GC.setColor(.4, .4, .4)
    GC.strokeDraw('full', 3, TEXTS.load, 800, 500, 0, 1.6, 2, TEXTS.load:getWidth() / 2, TEXTS.load:getHeight() / 2)
    GC.setColor(.6, .6, .6)
    GC.strokeDraw('full', 1, TEXTS.load, 800, 500, 0, 1.6, 2, TEXTS.load:getWidth() / 2, TEXTS.load:getHeight() / 2)
    GC.setColor(.9, .9, .9)
    GC.mDraw(TEXTS.load, 800, 500, 0, 1.6, 2)
end

return scene
